// SPDX-License-Identifier: BSD-3-Clause

// The admin API of fileshare: which shares exist, what they serve, and who may
// use them.
//
// It manages the shares IT created. A share written in the configuration files
// is listed, with the same fields, and a change to its definition is refused
// with FAILED_PRECONDITION: a share defined in two places is a question nobody
// wants to answer, and the file is where that one is defined. Taking it
// offline and back -- DisableShare, EnableShare -- is not a definition, and is
// allowed.
//
// Every change is applied before the call returns, and applying one restarts
// the protocol servers: their connections are closed, so a revocation reaches
// the sessions that were already open. A change the server cannot honour --
// an image that will not open, a name nobody in the directory has -- is
// refused, and what was being served is left as it was.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: fileshare/admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetServerInfo_FullMethodName   = "/fileshare.admin.v1.AdminService/GetServerInfo"
	AdminService_ListShares_FullMethodName      = "/fileshare.admin.v1.AdminService/ListShares"
	AdminService_GetShare_FullMethodName        = "/fileshare.admin.v1.AdminService/GetShare"
	AdminService_CreateShare_FullMethodName     = "/fileshare.admin.v1.AdminService/CreateShare"
	AdminService_UpdateShare_FullMethodName     = "/fileshare.admin.v1.AdminService/UpdateShare"
	AdminService_DeleteShare_FullMethodName     = "/fileshare.admin.v1.AdminService/DeleteShare"
	AdminService_DisableShare_FullMethodName    = "/fileshare.admin.v1.AdminService/DisableShare"
	AdminService_EnableShare_FullMethodName     = "/fileshare.admin.v1.AdminService/EnableShare"
	AdminService_Grant_FullMethodName           = "/fileshare.admin.v1.AdminService/Grant"
	AdminService_Revoke_FullMethodName          = "/fileshare.admin.v1.AdminService/Revoke"
	AdminService_ReloadDirectory_FullMethodName = "/fileshare.admin.v1.AdminService/ReloadDirectory"
	AdminService_ListUsers_FullMethodName       = "/fileshare.admin.v1.AdminService/ListUsers"
	AdminService_ListGroups_FullMethodName      = "/fileshare.admin.v1.AdminService/ListGroups"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
	ListShares(ctx context.Context, in *ListSharesRequest, opts ...grpc.CallOption) (*ListSharesResponse, error)
	GetShare(ctx context.Context, in *GetShareRequest, opts ...grpc.CallOption) (*GetShareResponse, error)
	// CreateShare needs at least one grant. A share with none is open to
	// anyone who authenticates, which the configuration file can say on
	// purpose and an API call should not say by omission.
	CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*CreateShareResponse, error)
	UpdateShare(ctx context.Context, in *UpdateShareRequest, opts ...grpc.CallOption) (*UpdateShareResponse, error)
	DeleteShare(ctx context.Context, in *DeleteShareRequest, opts ...grpc.CallOption) (*DeleteShareResponse, error)
	// DisableShare stops serving a share and keeps its definition, the way
	// Samba's `available = no` does: every attempt to connect fails, the
	// connections already open are closed, and its image or directory is let
	// go of -- so the file can be replaced while it is disabled. EnableShare
	// serves it again, and is refused when its source can no longer be opened.
	//
	// Unlike every other change, these apply to a share of the configuration
	// too: taking a share offline is an operation, not a definition. It is
	// kept in the state file, and a restart does not bring the share back.
	DisableShare(ctx context.Context, in *DisableShareRequest, opts ...grpc.CallOption) (*DisableShareResponse, error)
	EnableShare(ctx context.Context, in *EnableShareRequest, opts ...grpc.CallOption) (*EnableShareResponse, error)
	// Grant gives a subject access to a share, or changes the access it has.
	Grant(ctx context.Context, in *GrantRequest, opts ...grpc.CallOption) (*GrantResponse, error)
	// Revoke takes it away. Revoking the last grant is refused, for the reason
	// CreateShare needs one: delete the share instead.
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
	// ReloadDirectory reads the people again, now, rather than at the next
	// `reload` interval or SIGHUP. Only additions are applied in place; any
	// removal, changed credential, or share whose expanded lists changed
	// starts a new generation and closes the connections of the old one --
	// which is how disabling somebody in the directory reaches the sessions
	// they already have. A directory that cannot be read changes nothing, and
	// is UNAVAILABLE.
	ReloadDirectory(ctx context.Context, in *ReloadDirectoryRequest, opts ...grpc.CallOption) (*ReloadDirectoryResponse, error)
	// Who a grant can name.
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, AdminService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListShares(ctx context.Context, in *ListSharesRequest, opts ...grpc.CallOption) (*ListSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSharesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetShare(ctx context.Context, in *GetShareRequest, opts ...grpc.CallOption) (*GetShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShareResponse)
	err := c.cc.Invoke(ctx, AdminService_GetShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*CreateShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShareResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateShare(ctx context.Context, in *UpdateShareRequest, opts ...grpc.CallOption) (*UpdateShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateShareResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteShare(ctx context.Context, in *DeleteShareRequest, opts ...grpc.CallOption) (*DeleteShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShareResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DisableShare(ctx context.Context, in *DisableShareRequest, opts ...grpc.CallOption) (*DisableShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableShareResponse)
	err := c.cc.Invoke(ctx, AdminService_DisableShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) EnableShare(ctx context.Context, in *EnableShareRequest, opts ...grpc.CallOption) (*EnableShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableShareResponse)
	err := c.cc.Invoke(ctx, AdminService_EnableShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Grant(ctx context.Context, in *GrantRequest, opts ...grpc.CallOption) (*GrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantResponse)
	err := c.cc.Invoke(ctx, AdminService_Grant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, AdminService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ReloadDirectory(ctx context.Context, in *ReloadDirectoryRequest, opts ...grpc.CallOption) (*ReloadDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadDirectoryResponse)
	err := c.cc.Invoke(ctx, AdminService_ReloadDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, AdminService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	ListShares(context.Context, *ListSharesRequest) (*ListSharesResponse, error)
	GetShare(context.Context, *GetShareRequest) (*GetShareResponse, error)
	// CreateShare needs at least one grant. A share with none is open to
	// anyone who authenticates, which the configuration file can say on
	// purpose and an API call should not say by omission.
	CreateShare(context.Context, *CreateShareRequest) (*CreateShareResponse, error)
	UpdateShare(context.Context, *UpdateShareRequest) (*UpdateShareResponse, error)
	DeleteShare(context.Context, *DeleteShareRequest) (*DeleteShareResponse, error)
	// DisableShare stops serving a share and keeps its definition, the way
	// Samba's `available = no` does: every attempt to connect fails, the
	// connections already open are closed, and its image or directory is let
	// go of -- so the file can be replaced while it is disabled. EnableShare
	// serves it again, and is refused when its source can no longer be opened.
	//
	// Unlike every other change, these apply to a share of the configuration
	// too: taking a share offline is an operation, not a definition. It is
	// kept in the state file, and a restart does not bring the share back.
	DisableShare(context.Context, *DisableShareRequest) (*DisableShareResponse, error)
	EnableShare(context.Context, *EnableShareRequest) (*EnableShareResponse, error)
	// Grant gives a subject access to a share, or changes the access it has.
	Grant(context.Context, *GrantRequest) (*GrantResponse, error)
	// Revoke takes it away. Revoking the last grant is refused, for the reason
	// CreateShare needs one: delete the share instead.
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
	// ReloadDirectory reads the people again, now, rather than at the next
	// `reload` interval or SIGHUP. Only additions are applied in place; any
	// removal, changed credential, or share whose expanded lists changed
	// starts a new generation and closes the connections of the old one --
	// which is how disabling somebody in the directory reaches the sessions
	// they already have. A directory that cannot be read changes nothing, and
	// is UNAVAILABLE.
	ReloadDirectory(context.Context, *ReloadDirectoryRequest) (*ReloadDirectoryResponse, error)
	// Who a grant can name.
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedAdminServiceServer) ListShares(context.Context, *ListSharesRequest) (*ListSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShares not implemented")
}
func (UnimplementedAdminServiceServer) GetShare(context.Context, *GetShareRequest) (*GetShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShare not implemented")
}
func (UnimplementedAdminServiceServer) CreateShare(context.Context, *CreateShareRequest) (*CreateShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShare not implemented")
}
func (UnimplementedAdminServiceServer) UpdateShare(context.Context, *UpdateShareRequest) (*UpdateShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShare not implemented")
}
func (UnimplementedAdminServiceServer) DeleteShare(context.Context, *DeleteShareRequest) (*DeleteShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShare not implemented")
}
func (UnimplementedAdminServiceServer) DisableShare(context.Context, *DisableShareRequest) (*DisableShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableShare not implemented")
}
func (UnimplementedAdminServiceServer) EnableShare(context.Context, *EnableShareRequest) (*EnableShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableShare not implemented")
}
func (UnimplementedAdminServiceServer) Grant(context.Context, *GrantRequest) (*GrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Grant not implemented")
}
func (UnimplementedAdminServiceServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedAdminServiceServer) ReloadDirectory(context.Context, *ReloadDirectoryRequest) (*ReloadDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadDirectory not implemented")
}
func (UnimplementedAdminServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedAdminServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListShares(ctx, req.(*ListSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetShare(ctx, req.(*GetShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateShare(ctx, req.(*CreateShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateShare(ctx, req.(*UpdateShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteShare(ctx, req.(*DeleteShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DisableShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DisableShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DisableShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DisableShare(ctx, req.(*DisableShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_EnableShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).EnableShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_EnableShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).EnableShare(ctx, req.(*EnableShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Grant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Grant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Grant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Grant(ctx, req.(*GrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ReloadDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ReloadDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ReloadDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ReloadDirectory(ctx, req.(*ReloadDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileshare.admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerInfo",
			Handler:    _AdminService_GetServerInfo_Handler,
		},
		{
			MethodName: "ListShares",
			Handler:    _AdminService_ListShares_Handler,
		},
		{
			MethodName: "GetShare",
			Handler:    _AdminService_GetShare_Handler,
		},
		{
			MethodName: "CreateShare",
			Handler:    _AdminService_CreateShare_Handler,
		},
		{
			MethodName: "UpdateShare",
			Handler:    _AdminService_UpdateShare_Handler,
		},
		{
			MethodName: "DeleteShare",
			Handler:    _AdminService_DeleteShare_Handler,
		},
		{
			MethodName: "DisableShare",
			Handler:    _AdminService_DisableShare_Handler,
		},
		{
			MethodName: "EnableShare",
			Handler:    _AdminService_EnableShare_Handler,
		},
		{
			MethodName: "Grant",
			Handler:    _AdminService_Grant_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _AdminService_Revoke_Handler,
		},
		{
			MethodName: "ReloadDirectory",
			Handler:    _AdminService_ReloadDirectory_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _AdminService_ListUsers_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _AdminService_ListGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fileshare/admin/v1/admin.proto",
}
