// SPDX-License-Identifier: BSD-3-Clause

// The admin API of fileshare: which shares exist, what they serve, and who may
// use them.
//
// It manages the shares IT created. A share written in the configuration files
// is listed, with the same fields, and every change to it is refused with
// FAILED_PRECONDITION: a share defined in two places is a question nobody
// wants to answer, and the file is where that one is defined.
//
// Every change is applied before the call returns, and applying one restarts
// the protocol servers: their connections are closed, so a revocation reaches
// the sessions that were already open. A change the server cannot honour --
// an image that will not open, a name nobody in the directory has -- is
// refused, and what was being served is left as it was.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: fileshare/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Origin int32

const (
	Origin_ORIGIN_UNSPECIFIED Origin = 0
	// Written in a configuration file; read-only through this API.
	Origin_ORIGIN_CONFIG Origin = 1
	// Created through this API, and kept in its state file.
	Origin_ORIGIN_API Origin = 2
)

// Enum value maps for Origin.
var (
	Origin_name = map[int32]string{
		0: "ORIGIN_UNSPECIFIED",
		1: "ORIGIN_CONFIG",
		2: "ORIGIN_API",
	}
	Origin_value = map[string]int32{
		"ORIGIN_UNSPECIFIED": 0,
		"ORIGIN_CONFIG":      1,
		"ORIGIN_API":         2,
	}
)

func (x Origin) Enum() *Origin {
	p := new(Origin)
	*p = x
	return p
}

func (x Origin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Origin) Descriptor() protoreflect.EnumDescriptor {
	return file_fileshare_admin_v1_admin_proto_enumTypes[0].Descriptor()
}

func (Origin) Type() protoreflect.EnumType {
	return &file_fileshare_admin_v1_admin_proto_enumTypes[0]
}

func (x Origin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Origin.Descriptor instead.
func (Origin) EnumDescriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

type Access int32

const (
	Access_ACCESS_UNSPECIFIED Access = 0
	Access_ACCESS_READ        Access = 1
	Access_ACCESS_WRITE       Access = 2
)

// Enum value maps for Access.
var (
	Access_name = map[int32]string{
		0: "ACCESS_UNSPECIFIED",
		1: "ACCESS_READ",
		2: "ACCESS_WRITE",
	}
	Access_value = map[string]int32{
		"ACCESS_UNSPECIFIED": 0,
		"ACCESS_READ":        1,
		"ACCESS_WRITE":       2,
	}
)

func (x Access) Enum() *Access {
	p := new(Access)
	*p = x
	return p
}

func (x Access) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Access) Descriptor() protoreflect.EnumDescriptor {
	return file_fileshare_admin_v1_admin_proto_enumTypes[1].Descriptor()
}

func (Access) Type() protoreflect.EnumType {
	return &file_fileshare_admin_v1_admin_proto_enumTypes[1]
}

func (x Access) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Access.Descriptor instead.
func (Access) EnumDescriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

// Applied is what serving a change did.
type Applied struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generation now being served; see ServerInfo.generation.
	Generation uint64 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// How many connections the previous generation had open, and closed.
	ConnectionsClosed uint64 `protobuf:"varint,2,opt,name=connections_closed,json=connectionsClosed,proto3" json:"connections_closed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Applied) Reset() {
	*x = Applied{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Applied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Applied) ProtoMessage() {}

func (x *Applied) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Applied.ProtoReflect.Descriptor instead.
func (*Applied) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Applied) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Applied) GetConnectionsClosed() uint64 {
	if x != nil {
		return x.ConnectionsClosed
	}
	return 0
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

type GetServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ServerInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerInfoResponse) GetInfo() *ServerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ServerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the server calls itself to a client.
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Started *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started,proto3" json:"started,omitempty"`
	// How many lists of shares have been served since the start; it goes up by
	// one with every change applied.
	Generation    uint64      `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	Listeners     []*Listener `protobuf:"bytes,5,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *ServerInfo) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ServerInfo) GetListeners() []*Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type Listener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listener) Reset() {
	*x = Listener{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *Listener) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Listener) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSharesRequest) Reset() {
	*x = ListSharesRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharesRequest) ProtoMessage() {}

func (x *ListSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharesRequest.ProtoReflect.Descriptor instead.
func (*ListSharesRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

type ListSharesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shares        []*Share               `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSharesResponse) Reset() {
	*x = ListSharesResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharesResponse) ProtoMessage() {}

func (x *ListSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharesResponse.ProtoReflect.Descriptor instead.
func (*ListSharesResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListSharesResponse) GetShares() []*Share {
	if x != nil {
		return x.Shares
	}
	return nil
}

type GetShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareRequest) Reset() {
	*x = GetShareRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareRequest) ProtoMessage() {}

func (x *GetShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareRequest.ProtoReflect.Descriptor instead.
func (*GetShareRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *Share                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareResponse) Reset() {
	*x = GetShareResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareResponse) ProtoMessage() {}

func (x *GetShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareResponse.ProtoReflect.Descriptor instead.
func (*GetShareResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GetShareResponse) GetShare() *Share {
	if x != nil {
		return x.Share
	}
	return nil
}

// A Subject is who a grant is for, in the vocabulary the configuration file
// uses: a person, @group, oidc:groups:<value> or oidc:user:<name>.
type Subject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Subject_User
	//	*Subject_Group
	//	*Subject_OidcGroup
	//	*Subject_OidcUser
	Kind          isSubject_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *Subject) GetKind() isSubject_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Subject) GetUser() string {
	if x != nil {
		if x, ok := x.Kind.(*Subject_User); ok {
			return x.User
		}
	}
	return ""
}

func (x *Subject) GetGroup() string {
	if x != nil {
		if x, ok := x.Kind.(*Subject_Group); ok {
			return x.Group
		}
	}
	return ""
}

func (x *Subject) GetOidcGroup() string {
	if x != nil {
		if x, ok := x.Kind.(*Subject_OidcGroup); ok {
			return x.OidcGroup
		}
	}
	return ""
}

func (x *Subject) GetOidcUser() string {
	if x != nil {
		if x, ok := x.Kind.(*Subject_OidcUser); ok {
			return x.OidcUser
		}
	}
	return ""
}

type isSubject_Kind interface {
	isSubject_Kind()
}

type Subject_User struct {
	// Somebody in the directory.
	User string `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type Subject_Group struct {
	// A group of the directory, without the @.
	Group string `protobuf:"bytes,2,opt,name=group,proto3,oneof"`
}

type Subject_OidcGroup struct {
	// A value of the identity provider's groups claim.
	OidcGroup string `protobuf:"bytes,3,opt,name=oidc_group,json=oidcGroup,proto3,oneof"`
}

type Subject_OidcUser struct {
	// A name the identity provider vouches for.
	OidcUser string `protobuf:"bytes,4,opt,name=oidc_user,json=oidcUser,proto3,oneof"`
}

func (*Subject_User) isSubject_Kind() {}

func (*Subject_Group) isSubject_Kind() {}

func (*Subject_OidcGroup) isSubject_Kind() {}

func (*Subject_OidcUser) isSubject_Kind() {}

type Grant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Access        Access                 `protobuf:"varint,2,opt,name=access,proto3,enum=fileshare.admin.v1.Access" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grant.ProtoReflect.Descriptor instead.
func (*Grant) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *Grant) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Grant) GetAccess() Access {
	if x != nil {
		return x.Access
	}
	return Access_ACCESS_UNSPECIFIED
}

type Share struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*Share_Image
	//	*Share_Directory
	Source isShare_Source `protobuf_oneof:"source"`
	Origin Origin         `protobuf:"varint,4,opt,name=origin,proto3,enum=fileshare.admin.v1.Origin" json:"origin,omitempty"`
	// What was asked.
	ReadOnly bool `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// What is served: read-only as asked, or because the source cannot take a
	// write -- a device, a chosen partition, a file that would not open for
	// writing -- or because nobody was granted ACCESS_WRITE.
	EffectiveReadOnly bool `protobuf:"varint,6,opt,name=effective_read_only,json=effectiveReadOnly,proto3" json:"effective_read_only,omitempty"`
	// The filesystem found or named in an image, or "directory".
	Filesystem string `protobuf:"bytes,7,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	// Which protocols may carry it; empty means every one that can honour it.
	Protocols []string `protobuf:"bytes,8,rep,name=protocols,proto3" json:"protocols,omitempty"`
	// For a configuration share, what its allow and writers lists mean.
	Grants []*Grant `protobuf:"bytes,9,rep,name=grants,proto3" json:"grants,omitempty"`
	// Which protocols serve it now, and why the others do not.
	ServedOver []string   `protobuf:"bytes,10,rep,name=served_over,json=servedOver,proto3" json:"served_over,omitempty"`
	Refusals   []*Refusal `protobuf:"bytes,11,rep,name=refusals,proto3" json:"refusals,omitempty"`
	SizeBytes  uint64     `protobuf:"varint,12,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// False when DisableShare took it offline. A disabled share is listed with
	// what it would serve, and serves nothing.
	Enabled       bool `protobuf:"varint,13,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Share) Reset() {
	*x = Share{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share) ProtoMessage() {}

func (x *Share) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share.ProtoReflect.Descriptor instead.
func (*Share) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *Share) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Share) GetSource() isShare_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Share) GetImage() string {
	if x != nil {
		if x, ok := x.Source.(*Share_Image); ok {
			return x.Image
		}
	}
	return ""
}

func (x *Share) GetDirectory() string {
	if x != nil {
		if x, ok := x.Source.(*Share_Directory); ok {
			return x.Directory
		}
	}
	return ""
}

func (x *Share) GetOrigin() Origin {
	if x != nil {
		return x.Origin
	}
	return Origin_ORIGIN_UNSPECIFIED
}

func (x *Share) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Share) GetEffectiveReadOnly() bool {
	if x != nil {
		return x.EffectiveReadOnly
	}
	return false
}

func (x *Share) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *Share) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Share) GetGrants() []*Grant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *Share) GetServedOver() []string {
	if x != nil {
		return x.ServedOver
	}
	return nil
}

func (x *Share) GetRefusals() []*Refusal {
	if x != nil {
		return x.Refusals
	}
	return nil
}

func (x *Share) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Share) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type isShare_Source interface {
	isShare_Source()
}

type Share_Image struct {
	// A disk image, or a device.
	Image string `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type Share_Directory struct {
	// A directory tree of the host.
	Directory string `protobuf:"bytes,3,opt,name=directory,proto3,oneof"`
}

func (*Share_Image) isShare_Source() {}

func (*Share_Directory) isShare_Source() {}

type Refusal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refusal) Reset() {
	*x = Refusal{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refusal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refusal) ProtoMessage() {}

func (x *Refusal) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refusal.ProtoReflect.Descriptor instead.
func (*Refusal) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *Refusal) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Refusal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateShareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Either one must lie under one of the admin block's source_roots.
	//
	// Types that are valid to be assigned to Source:
	//
	//	*CreateShareRequest_Image
	//	*CreateShareRequest_Directory
	Source   isCreateShareRequest_Source `protobuf_oneof:"source"`
	ReadOnly bool                        `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// For an image only: the same fields as a share block.
	Filesystem     string   `protobuf:"bytes,5,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Partition      *int32   `protobuf:"varint,6,opt,name=partition,proto3,oneof" json:"partition,omitempty"`
	PartitionLabel string   `protobuf:"bytes,7,opt,name=partition_label,json=partitionLabel,proto3" json:"partition_label,omitempty"`
	PartitionUuid  string   `protobuf:"bytes,8,opt,name=partition_uuid,json=partitionUuid,proto3" json:"partition_uuid,omitempty"`
	Protocols      []string `protobuf:"bytes,9,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Grants         []*Grant `protobuf:"bytes,10,rep,name=grants,proto3" json:"grants,omitempty"`
	// Create it disabled: defined, checked, and not served until EnableShare.
	Disabled      bool `protobuf:"varint,11,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareRequest) Reset() {
	*x = CreateShareRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareRequest) ProtoMessage() {}

func (x *CreateShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareRequest.ProtoReflect.Descriptor instead.
func (*CreateShareRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *CreateShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateShareRequest) GetSource() isCreateShareRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CreateShareRequest) GetImage() string {
	if x != nil {
		if x, ok := x.Source.(*CreateShareRequest_Image); ok {
			return x.Image
		}
	}
	return ""
}

func (x *CreateShareRequest) GetDirectory() string {
	if x != nil {
		if x, ok := x.Source.(*CreateShareRequest_Directory); ok {
			return x.Directory
		}
	}
	return ""
}

func (x *CreateShareRequest) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *CreateShareRequest) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *CreateShareRequest) GetPartition() int32 {
	if x != nil && x.Partition != nil {
		return *x.Partition
	}
	return 0
}

func (x *CreateShareRequest) GetPartitionLabel() string {
	if x != nil {
		return x.PartitionLabel
	}
	return ""
}

func (x *CreateShareRequest) GetPartitionUuid() string {
	if x != nil {
		return x.PartitionUuid
	}
	return ""
}

func (x *CreateShareRequest) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *CreateShareRequest) GetGrants() []*Grant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *CreateShareRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type isCreateShareRequest_Source interface {
	isCreateShareRequest_Source()
}

type CreateShareRequest_Image struct {
	Image string `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type CreateShareRequest_Directory struct {
	Directory string `protobuf:"bytes,3,opt,name=directory,proto3,oneof"`
}

func (*CreateShareRequest_Image) isCreateShareRequest_Source() {}

func (*CreateShareRequest_Directory) isCreateShareRequest_Source() {}

type CreateShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *Share                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Applied       *Applied               `protobuf:"bytes,2,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareResponse) Reset() {
	*x = CreateShareResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareResponse) ProtoMessage() {}

func (x *CreateShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareResponse.ProtoReflect.Descriptor instead.
func (*CreateShareResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *CreateShareResponse) GetShare() *Share {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *CreateShareResponse) GetApplied() *Applied {
	if x != nil {
		return x.Applied
	}
	return nil
}

// The fields of a share that can change without it becoming another share.
// Its source cannot: delete it and create another.
type UpdateShareRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadOnly *bool                  `protobuf:"varint,2,opt,name=read_only,json=readOnly,proto3,oneof" json:"read_only,omitempty"`
	// Replaces the list when present; an empty list means every protocol.
	Protocols     *ProtocolList `protobuf:"bytes,3,opt,name=protocols,proto3" json:"protocols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShareRequest) Reset() {
	*x = UpdateShareRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShareRequest) ProtoMessage() {}

func (x *UpdateShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShareRequest.ProtoReflect.Descriptor instead.
func (*UpdateShareRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateShareRequest) GetReadOnly() bool {
	if x != nil && x.ReadOnly != nil {
		return *x.ReadOnly
	}
	return false
}

func (x *UpdateShareRequest) GetProtocols() *ProtocolList {
	if x != nil {
		return x.Protocols
	}
	return nil
}

type UpdateShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *Share                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Applied       *Applied               `protobuf:"bytes,2,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShareResponse) Reset() {
	*x = UpdateShareResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShareResponse) ProtoMessage() {}

func (x *UpdateShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShareResponse.ProtoReflect.Descriptor instead.
func (*UpdateShareResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateShareResponse) GetShare() *Share {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *UpdateShareResponse) GetApplied() *Applied {
	if x != nil {
		return x.Applied
	}
	return nil
}

type ProtocolList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolList) Reset() {
	*x = ProtocolList{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolList) ProtoMessage() {}

func (x *ProtocolList) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolList.ProtoReflect.Descriptor instead.
func (*ProtocolList) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ProtocolList) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type DeleteShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShareRequest) Reset() {
	*x = DeleteShareRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShareRequest) ProtoMessage() {}

func (x *DeleteShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShareRequest.ProtoReflect.Descriptor instead.
func (*DeleteShareRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       *Applied               `protobuf:"bytes,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShareResponse) Reset() {
	*x = DeleteShareResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShareResponse) ProtoMessage() {}

func (x *DeleteShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShareResponse.ProtoReflect.Descriptor instead.
func (*DeleteShareResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteShareResponse) GetApplied() *Applied {
	if x != nil {
		return x.Applied
	}
	return nil
}

type DisableShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableShareRequest) Reset() {
	*x = DisableShareRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableShareRequest) ProtoMessage() {}

func (x *DisableShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableShareRequest.ProtoReflect.Descriptor instead.
func (*DisableShareRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *DisableShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DisableShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *Share                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Applied       *Applied               `protobuf:"bytes,2,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableShareResponse) Reset() {
	*x = DisableShareResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableShareResponse) ProtoMessage() {}

func (x *DisableShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableShareResponse.ProtoReflect.Descriptor instead.
func (*DisableShareResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *DisableShareResponse) GetShare() *Share {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *DisableShareResponse) GetApplied() *Applied {
	if x != nil {
		return x.Applied
	}
	return nil
}

type EnableShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableShareRequest) Reset() {
	*x = EnableShareRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableShareRequest) ProtoMessage() {}

func (x *EnableShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableShareRequest.ProtoReflect.Descriptor instead.
func (*EnableShareRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *EnableShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnableShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *Share                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Applied       *Applied               `protobuf:"bytes,2,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableShareResponse) Reset() {
	*x = EnableShareResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableShareResponse) ProtoMessage() {}

func (x *EnableShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableShareResponse.ProtoReflect.Descriptor instead.
func (*EnableShareResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *EnableShareResponse) GetShare() *Share {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *EnableShareResponse) GetApplied() *Applied {
	if x != nil {
		return x.Applied
	}
	return nil
}

type GrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         string                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Grant         *Grant                 `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRequest) Reset() {
	*x = GrantRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRequest) ProtoMessage() {}

func (x *GrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRequest.ProtoReflect.Descriptor instead.
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *GrantRequest) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *GrantRequest) GetGrant() *Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

type GrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *Share                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Applied       *Applied               `protobuf:"bytes,2,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantResponse) Reset() {
	*x = GrantResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantResponse) ProtoMessage() {}

func (x *GrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantResponse.ProtoReflect.Descriptor instead.
func (*GrantResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *GrantResponse) GetShare() *Share {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *GrantResponse) GetApplied() *Applied {
	if x != nil {
		return x.Applied
	}
	return nil
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         string                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Subject       *Subject               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *RevokeRequest) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *RevokeRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *Share                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Applied       *Applied               `protobuf:"bytes,2,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *RevokeResponse) GetShare() *Share {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *RevokeResponse) GetApplied() *Applied {
	if x != nil {
		return x.Applied
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{28}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Which source knows them.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// The served protocols their credentials can answer.
	CanUse        []string `protobuf:"bytes,3,rep,name=can_use,json=canUse,proto3" json:"can_use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *User) GetCanUse() []string {
	if x != nil {
		return x.CanUse
	}
	return nil
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{31}
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{32}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Members       []string               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_admin_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_fileshare_admin_v1_admin_proto_rawDescGZIP(), []int{33}
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_fileshare_admin_v1_admin_proto protoreflect.FileDescriptor

const file_fileshare_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1efileshare/admin/v1/admin.proto\x12\x12fileshare.admin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\aApplied\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12-\n" +
	"\x12connections_closed\x18\x02 \x01(\x04R\x11connectionsClosed\"\x16\n" +
	"\x14GetServerInfoRequest\"K\n" +
	"\x15GetServerInfoResponse\x122\n" +
	"\x04info\x18\x01 \x01(\v2\x1e.fileshare.admin.v1.ServerInfoR\x04info\"\xcc\x01\n" +
	"\n" +
	"ServerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x124\n" +
	"\astarted\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astarted\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x04R\n" +
	"generation\x12:\n" +
	"\tlisteners\x18\x05 \x03(\v2\x1c.fileshare.admin.v1.ListenerR\tlisteners\"@\n" +
	"\bListener\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x13\n" +
	"\x11ListSharesRequest\"G\n" +
	"\x12ListSharesResponse\x121\n" +
	"\x06shares\x18\x01 \x03(\v2\x19.fileshare.admin.v1.ShareR\x06shares\"%\n" +
	"\x0fGetShareRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"C\n" +
	"\x10GetShareResponse\x12/\n" +
	"\x05share\x18\x01 \x01(\v2\x19.fileshare.admin.v1.ShareR\x05share\"\x7f\n" +
	"\aSubject\x12\x14\n" +
	"\x04user\x18\x01 \x01(\tH\x00R\x04user\x12\x16\n" +
	"\x05group\x18\x02 \x01(\tH\x00R\x05group\x12\x1f\n" +
	"\n" +
	"oidc_group\x18\x03 \x01(\tH\x00R\toidcGroup\x12\x1d\n" +
	"\toidc_user\x18\x04 \x01(\tH\x00R\boidcUserB\x06\n" +
	"\x04kind\"r\n" +
	"\x05Grant\x125\n" +
	"\asubject\x18\x01 \x01(\v2\x1b.fileshare.admin.v1.SubjectR\asubject\x122\n" +
	"\x06access\x18\x02 \x01(\x0e2\x1a.fileshare.admin.v1.AccessR\x06access\"\xe2\x03\n" +
	"\x05Share\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x05image\x18\x02 \x01(\tH\x00R\x05image\x12\x1e\n" +
	"\tdirectory\x18\x03 \x01(\tH\x00R\tdirectory\x122\n" +
	"\x06origin\x18\x04 \x01(\x0e2\x1a.fileshare.admin.v1.OriginR\x06origin\x12\x1b\n" +
	"\tread_only\x18\x05 \x01(\bR\breadOnly\x12.\n" +
	"\x13effective_read_only\x18\x06 \x01(\bR\x11effectiveReadOnly\x12\x1e\n" +
	"\n" +
	"filesystem\x18\a \x01(\tR\n" +
	"filesystem\x12\x1c\n" +
	"\tprotocols\x18\b \x03(\tR\tprotocols\x121\n" +
	"\x06grants\x18\t \x03(\v2\x19.fileshare.admin.v1.GrantR\x06grants\x12\x1f\n" +
	"\vserved_over\x18\n" +
	" \x03(\tR\n" +
	"servedOver\x127\n" +
	"\brefusals\x18\v \x03(\v2\x1b.fileshare.admin.v1.RefusalR\brefusals\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\f \x01(\x04R\tsizeBytes\x12\x18\n" +
	"\aenabled\x18\r \x01(\bR\aenabledB\b\n" +
	"\x06source\"=\n" +
	"\aRefusal\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x95\x03\n" +
	"\x12CreateShareRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x05image\x18\x02 \x01(\tH\x00R\x05image\x12\x1e\n" +
	"\tdirectory\x18\x03 \x01(\tH\x00R\tdirectory\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x05 \x01(\tR\n" +
	"filesystem\x12!\n" +
	"\tpartition\x18\x06 \x01(\x05H\x01R\tpartition\x88\x01\x01\x12'\n" +
	"\x0fpartition_label\x18\a \x01(\tR\x0epartitionLabel\x12%\n" +
	"\x0epartition_uuid\x18\b \x01(\tR\rpartitionUuid\x12\x1c\n" +
	"\tprotocols\x18\t \x03(\tR\tprotocols\x121\n" +
	"\x06grants\x18\n" +
	" \x03(\v2\x19.fileshare.admin.v1.GrantR\x06grants\x12\x1a\n" +
	"\bdisabled\x18\v \x01(\bR\bdisabledB\b\n" +
	"\x06sourceB\f\n" +
	"\n" +
	"_partition\"}\n" +
	"\x13CreateShareResponse\x12/\n" +
	"\x05share\x18\x01 \x01(\v2\x19.fileshare.admin.v1.ShareR\x05share\x125\n" +
	"\aapplied\x18\x02 \x01(\v2\x1b.fileshare.admin.v1.AppliedR\aapplied\"\x98\x01\n" +
	"\x12UpdateShareRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\tread_only\x18\x02 \x01(\bH\x00R\breadOnly\x88\x01\x01\x12>\n" +
	"\tprotocols\x18\x03 \x01(\v2 .fileshare.admin.v1.ProtocolListR\tprotocolsB\f\n" +
	"\n" +
	"_read_only\"}\n" +
	"\x13UpdateShareResponse\x12/\n" +
	"\x05share\x18\x01 \x01(\v2\x19.fileshare.admin.v1.ShareR\x05share\x125\n" +
	"\aapplied\x18\x02 \x01(\v2\x1b.fileshare.admin.v1.AppliedR\aapplied\"$\n" +
	"\fProtocolList\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"(\n" +
	"\x12DeleteShareRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x13DeleteShareResponse\x125\n" +
	"\aapplied\x18\x01 \x01(\v2\x1b.fileshare.admin.v1.AppliedR\aapplied\")\n" +
	"\x13DisableShareRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"~\n" +
	"\x14DisableShareResponse\x12/\n" +
	"\x05share\x18\x01 \x01(\v2\x19.fileshare.admin.v1.ShareR\x05share\x125\n" +
	"\aapplied\x18\x02 \x01(\v2\x1b.fileshare.admin.v1.AppliedR\aapplied\"(\n" +
	"\x12EnableShareRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"}\n" +
	"\x13EnableShareResponse\x12/\n" +
	"\x05share\x18\x01 \x01(\v2\x19.fileshare.admin.v1.ShareR\x05share\x125\n" +
	"\aapplied\x18\x02 \x01(\v2\x1b.fileshare.admin.v1.AppliedR\aapplied\"U\n" +
	"\fGrantRequest\x12\x14\n" +
	"\x05share\x18\x01 \x01(\tR\x05share\x12/\n" +
	"\x05grant\x18\x02 \x01(\v2\x19.fileshare.admin.v1.GrantR\x05grant\"w\n" +
	"\rGrantResponse\x12/\n" +
	"\x05share\x18\x01 \x01(\v2\x19.fileshare.admin.v1.ShareR\x05share\x125\n" +
	"\aapplied\x18\x02 \x01(\v2\x1b.fileshare.admin.v1.AppliedR\aapplied\"\\\n" +
	"\rRevokeRequest\x12\x14\n" +
	"\x05share\x18\x01 \x01(\tR\x05share\x125\n" +
	"\asubject\x18\x02 \x01(\v2\x1b.fileshare.admin.v1.SubjectR\asubject\"x\n" +
	"\x0eRevokeResponse\x12/\n" +
	"\x05share\x18\x01 \x01(\v2\x19.fileshare.admin.v1.ShareR\x05share\x125\n" +
	"\aapplied\x18\x02 \x01(\v2\x1b.fileshare.admin.v1.AppliedR\aapplied\"\x12\n" +
	"\x10ListUsersRequest\"C\n" +
	"\x11ListUsersResponse\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.fileshare.admin.v1.UserR\x05users\"K\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x17\n" +
	"\acan_use\x18\x03 \x03(\tR\x06canUse\"\x13\n" +
	"\x11ListGroupsRequest\"G\n" +
	"\x12ListGroupsResponse\x121\n" +
	"\x06groups\x18\x01 \x03(\v2\x19.fileshare.admin.v1.GroupR\x06groups\"5\n" +
	"\x05Group\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers*C\n" +
	"\x06Origin\x12\x16\n" +
	"\x12ORIGIN_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rORIGIN_CONFIG\x10\x01\x12\x0e\n" +
	"\n" +
	"ORIGIN_API\x10\x02*C\n" +
	"\x06Access\x12\x16\n" +
	"\x12ACCESS_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vACCESS_READ\x10\x01\x12\x10\n" +
	"\fACCESS_WRITE\x10\x022\xe1\b\n" +
	"\fAdminService\x12d\n" +
	"\rGetServerInfo\x12(.fileshare.admin.v1.GetServerInfoRequest\x1a).fileshare.admin.v1.GetServerInfoResponse\x12[\n" +
	"\n" +
	"ListShares\x12%.fileshare.admin.v1.ListSharesRequest\x1a&.fileshare.admin.v1.ListSharesResponse\x12U\n" +
	"\bGetShare\x12#.fileshare.admin.v1.GetShareRequest\x1a$.fileshare.admin.v1.GetShareResponse\x12^\n" +
	"\vCreateShare\x12&.fileshare.admin.v1.CreateShareRequest\x1a'.fileshare.admin.v1.CreateShareResponse\x12^\n" +
	"\vUpdateShare\x12&.fileshare.admin.v1.UpdateShareRequest\x1a'.fileshare.admin.v1.UpdateShareResponse\x12^\n" +
	"\vDeleteShare\x12&.fileshare.admin.v1.DeleteShareRequest\x1a'.fileshare.admin.v1.DeleteShareResponse\x12a\n" +
	"\fDisableShare\x12'.fileshare.admin.v1.DisableShareRequest\x1a(.fileshare.admin.v1.DisableShareResponse\x12^\n" +
	"\vEnableShare\x12&.fileshare.admin.v1.EnableShareRequest\x1a'.fileshare.admin.v1.EnableShareResponse\x12L\n" +
	"\x05Grant\x12 .fileshare.admin.v1.GrantRequest\x1a!.fileshare.admin.v1.GrantResponse\x12O\n" +
	"\x06Revoke\x12!.fileshare.admin.v1.RevokeRequest\x1a\".fileshare.admin.v1.RevokeResponse\x12X\n" +
	"\tListUsers\x12$.fileshare.admin.v1.ListUsersRequest\x1a%.fileshare.admin.v1.ListUsersResponse\x12[\n" +
	"\n" +
	"ListGroups\x12%.fileshare.admin.v1.ListGroupsRequest\x1a&.fileshare.admin.v1.ListGroupsResponseBDZBgithub.com/go-fileshare/fileshare/proto/fileshare/admin/v1;adminv1b\x06proto3"

var (
	file_fileshare_admin_v1_admin_proto_rawDescOnce sync.Once
	file_fileshare_admin_v1_admin_proto_rawDescData []byte
)

func file_fileshare_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_fileshare_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_fileshare_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fileshare_admin_v1_admin_proto_rawDesc), len(file_fileshare_admin_v1_admin_proto_rawDesc)))
	})
	return file_fileshare_admin_v1_admin_proto_rawDescData
}

var file_fileshare_admin_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fileshare_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_fileshare_admin_v1_admin_proto_goTypes = []any{
	(Origin)(0),                   // 0: fileshare.admin.v1.Origin
	(Access)(0),                   // 1: fileshare.admin.v1.Access
	(*Applied)(nil),               // 2: fileshare.admin.v1.Applied
	(*GetServerInfoRequest)(nil),  // 3: fileshare.admin.v1.GetServerInfoRequest
	(*GetServerInfoResponse)(nil), // 4: fileshare.admin.v1.GetServerInfoResponse
	(*ServerInfo)(nil),            // 5: fileshare.admin.v1.ServerInfo
	(*Listener)(nil),              // 6: fileshare.admin.v1.Listener
	(*ListSharesRequest)(nil),     // 7: fileshare.admin.v1.ListSharesRequest
	(*ListSharesResponse)(nil),    // 8: fileshare.admin.v1.ListSharesResponse
	(*GetShareRequest)(nil),       // 9: fileshare.admin.v1.GetShareRequest
	(*GetShareResponse)(nil),      // 10: fileshare.admin.v1.GetShareResponse
	(*Subject)(nil),               // 11: fileshare.admin.v1.Subject
	(*Grant)(nil),                 // 12: fileshare.admin.v1.Grant
	(*Share)(nil),                 // 13: fileshare.admin.v1.Share
	(*Refusal)(nil),               // 14: fileshare.admin.v1.Refusal
	(*CreateShareRequest)(nil),    // 15: fileshare.admin.v1.CreateShareRequest
	(*CreateShareResponse)(nil),   // 16: fileshare.admin.v1.CreateShareResponse
	(*UpdateShareRequest)(nil),    // 17: fileshare.admin.v1.UpdateShareRequest
	(*UpdateShareResponse)(nil),   // 18: fileshare.admin.v1.UpdateShareResponse
	(*ProtocolList)(nil),          // 19: fileshare.admin.v1.ProtocolList
	(*DeleteShareRequest)(nil),    // 20: fileshare.admin.v1.DeleteShareRequest
	(*DeleteShareResponse)(nil),   // 21: fileshare.admin.v1.DeleteShareResponse
	(*DisableShareRequest)(nil),   // 22: fileshare.admin.v1.DisableShareRequest
	(*DisableShareResponse)(nil),  // 23: fileshare.admin.v1.DisableShareResponse
	(*EnableShareRequest)(nil),    // 24: fileshare.admin.v1.EnableShareRequest
	(*EnableShareResponse)(nil),   // 25: fileshare.admin.v1.EnableShareResponse
	(*GrantRequest)(nil),          // 26: fileshare.admin.v1.GrantRequest
	(*GrantResponse)(nil),         // 27: fileshare.admin.v1.GrantResponse
	(*RevokeRequest)(nil),         // 28: fileshare.admin.v1.RevokeRequest
	(*RevokeResponse)(nil),        // 29: fileshare.admin.v1.RevokeResponse
	(*ListUsersRequest)(nil),      // 30: fileshare.admin.v1.ListUsersRequest
	(*ListUsersResponse)(nil),     // 31: fileshare.admin.v1.ListUsersResponse
	(*User)(nil),                  // 32: fileshare.admin.v1.User
	(*ListGroupsRequest)(nil),     // 33: fileshare.admin.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),    // 34: fileshare.admin.v1.ListGroupsResponse
	(*Group)(nil),                 // 35: fileshare.admin.v1.Group
	(*timestamppb.Timestamp)(nil), // 36: google.protobuf.Timestamp
}
var file_fileshare_admin_v1_admin_proto_depIdxs = []int32{
	5,  // 0: fileshare.admin.v1.GetServerInfoResponse.info:type_name -> fileshare.admin.v1.ServerInfo
	36, // 1: fileshare.admin.v1.ServerInfo.started:type_name -> google.protobuf.Timestamp
	6,  // 2: fileshare.admin.v1.ServerInfo.listeners:type_name -> fileshare.admin.v1.Listener
	13, // 3: fileshare.admin.v1.ListSharesResponse.shares:type_name -> fileshare.admin.v1.Share
	13, // 4: fileshare.admin.v1.GetShareResponse.share:type_name -> fileshare.admin.v1.Share
	11, // 5: fileshare.admin.v1.Grant.subject:type_name -> fileshare.admin.v1.Subject
	1,  // 6: fileshare.admin.v1.Grant.access:type_name -> fileshare.admin.v1.Access
	0,  // 7: fileshare.admin.v1.Share.origin:type_name -> fileshare.admin.v1.Origin
	12, // 8: fileshare.admin.v1.Share.grants:type_name -> fileshare.admin.v1.Grant
	14, // 9: fileshare.admin.v1.Share.refusals:type_name -> fileshare.admin.v1.Refusal
	12, // 10: fileshare.admin.v1.CreateShareRequest.grants:type_name -> fileshare.admin.v1.Grant
	13, // 11: fileshare.admin.v1.CreateShareResponse.share:type_name -> fileshare.admin.v1.Share
	2,  // 12: fileshare.admin.v1.CreateShareResponse.applied:type_name -> fileshare.admin.v1.Applied
	19, // 13: fileshare.admin.v1.UpdateShareRequest.protocols:type_name -> fileshare.admin.v1.ProtocolList
	13, // 14: fileshare.admin.v1.UpdateShareResponse.share:type_name -> fileshare.admin.v1.Share
	2,  // 15: fileshare.admin.v1.UpdateShareResponse.applied:type_name -> fileshare.admin.v1.Applied
	2,  // 16: fileshare.admin.v1.DeleteShareResponse.applied:type_name -> fileshare.admin.v1.Applied
	13, // 17: fileshare.admin.v1.DisableShareResponse.share:type_name -> fileshare.admin.v1.Share
	2,  // 18: fileshare.admin.v1.DisableShareResponse.applied:type_name -> fileshare.admin.v1.Applied
	13, // 19: fileshare.admin.v1.EnableShareResponse.share:type_name -> fileshare.admin.v1.Share
	2,  // 20: fileshare.admin.v1.EnableShareResponse.applied:type_name -> fileshare.admin.v1.Applied
	12, // 21: fileshare.admin.v1.GrantRequest.grant:type_name -> fileshare.admin.v1.Grant
	13, // 22: fileshare.admin.v1.GrantResponse.share:type_name -> fileshare.admin.v1.Share
	2,  // 23: fileshare.admin.v1.GrantResponse.applied:type_name -> fileshare.admin.v1.Applied
	11, // 24: fileshare.admin.v1.RevokeRequest.subject:type_name -> fileshare.admin.v1.Subject
	13, // 25: fileshare.admin.v1.RevokeResponse.share:type_name -> fileshare.admin.v1.Share
	2,  // 26: fileshare.admin.v1.RevokeResponse.applied:type_name -> fileshare.admin.v1.Applied
	32, // 27: fileshare.admin.v1.ListUsersResponse.users:type_name -> fileshare.admin.v1.User
	35, // 28: fileshare.admin.v1.ListGroupsResponse.groups:type_name -> fileshare.admin.v1.Group
	3,  // 29: fileshare.admin.v1.AdminService.GetServerInfo:input_type -> fileshare.admin.v1.GetServerInfoRequest
	7,  // 30: fileshare.admin.v1.AdminService.ListShares:input_type -> fileshare.admin.v1.ListSharesRequest
	9,  // 31: fileshare.admin.v1.AdminService.GetShare:input_type -> fileshare.admin.v1.GetShareRequest
	15, // 32: fileshare.admin.v1.AdminService.CreateShare:input_type -> fileshare.admin.v1.CreateShareRequest
	17, // 33: fileshare.admin.v1.AdminService.UpdateShare:input_type -> fileshare.admin.v1.UpdateShareRequest
	20, // 34: fileshare.admin.v1.AdminService.DeleteShare:input_type -> fileshare.admin.v1.DeleteShareRequest
	22, // 35: fileshare.admin.v1.AdminService.DisableShare:input_type -> fileshare.admin.v1.DisableShareRequest
	24, // 36: fileshare.admin.v1.AdminService.EnableShare:input_type -> fileshare.admin.v1.EnableShareRequest
	26, // 37: fileshare.admin.v1.AdminService.Grant:input_type -> fileshare.admin.v1.GrantRequest
	28, // 38: fileshare.admin.v1.AdminService.Revoke:input_type -> fileshare.admin.v1.RevokeRequest
	30, // 39: fileshare.admin.v1.AdminService.ListUsers:input_type -> fileshare.admin.v1.ListUsersRequest
	33, // 40: fileshare.admin.v1.AdminService.ListGroups:input_type -> fileshare.admin.v1.ListGroupsRequest
	4,  // 41: fileshare.admin.v1.AdminService.GetServerInfo:output_type -> fileshare.admin.v1.GetServerInfoResponse
	8,  // 42: fileshare.admin.v1.AdminService.ListShares:output_type -> fileshare.admin.v1.ListSharesResponse
	10, // 43: fileshare.admin.v1.AdminService.GetShare:output_type -> fileshare.admin.v1.GetShareResponse
	16, // 44: fileshare.admin.v1.AdminService.CreateShare:output_type -> fileshare.admin.v1.CreateShareResponse
	18, // 45: fileshare.admin.v1.AdminService.UpdateShare:output_type -> fileshare.admin.v1.UpdateShareResponse
	21, // 46: fileshare.admin.v1.AdminService.DeleteShare:output_type -> fileshare.admin.v1.DeleteShareResponse
	23, // 47: fileshare.admin.v1.AdminService.DisableShare:output_type -> fileshare.admin.v1.DisableShareResponse
	25, // 48: fileshare.admin.v1.AdminService.EnableShare:output_type -> fileshare.admin.v1.EnableShareResponse
	27, // 49: fileshare.admin.v1.AdminService.Grant:output_type -> fileshare.admin.v1.GrantResponse
	29, // 50: fileshare.admin.v1.AdminService.Revoke:output_type -> fileshare.admin.v1.RevokeResponse
	31, // 51: fileshare.admin.v1.AdminService.ListUsers:output_type -> fileshare.admin.v1.ListUsersResponse
	34, // 52: fileshare.admin.v1.AdminService.ListGroups:output_type -> fileshare.admin.v1.ListGroupsResponse
	41, // [41:53] is the sub-list for method output_type
	29, // [29:41] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_fileshare_admin_v1_admin_proto_init() }
func file_fileshare_admin_v1_admin_proto_init() {
	if File_fileshare_admin_v1_admin_proto != nil {
		return
	}
	file_fileshare_admin_v1_admin_proto_msgTypes[9].OneofWrappers = []any{
		(*Subject_User)(nil),
		(*Subject_Group)(nil),
		(*Subject_OidcGroup)(nil),
		(*Subject_OidcUser)(nil),
	}
	file_fileshare_admin_v1_admin_proto_msgTypes[11].OneofWrappers = []any{
		(*Share_Image)(nil),
		(*Share_Directory)(nil),
	}
	file_fileshare_admin_v1_admin_proto_msgTypes[13].OneofWrappers = []any{
		(*CreateShareRequest_Image)(nil),
		(*CreateShareRequest_Directory)(nil),
	}
	file_fileshare_admin_v1_admin_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fileshare_admin_v1_admin_proto_rawDesc), len(file_fileshare_admin_v1_admin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileshare_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_fileshare_admin_v1_admin_proto_depIdxs,
		EnumInfos:         file_fileshare_admin_v1_admin_proto_enumTypes,
		MessageInfos:      file_fileshare_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_fileshare_admin_v1_admin_proto = out.File
	file_fileshare_admin_v1_admin_proto_goTypes = nil
	file_fileshare_admin_v1_admin_proto_depIdxs = nil
}
