// SPDX-License-Identifier: BSD-3-Clause

// The admin API of fileshare: which shares exist, what they serve, and who may
// use them.
//
// It manages the shares IT created. A share written in the configuration files
// is listed, with the same fields, and a change to its definition is refused
// with FAILED_PRECONDITION: a share defined in two places is a question nobody
// wants to answer, and the file is where that one is defined. Taking it
// offline and back -- DisableShare, EnableShare -- is not a definition, and is
// allowed.
//
// Every change is applied before the call returns, and applying one restarts
// the protocol servers: their connections are closed, so a revocation reaches
// the sessions that were already open. A change the server cannot honour --
// an image that will not open, a name nobody in the directory has -- is
// refused, and what was being served is left as it was.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: fileshare/admin/v1/admin.proto

package adminv1connect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	v1 "github.com/go-fileshare/fileshare/proto/fileshare/admin/v1"
	sync "sync"
)

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "fileshare.admin.v1.AdminService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceGetServerInfoProcedure is the procedure name of the AdminService's GetServerInfo RPC.
	AdminServiceGetServerInfoProcedure = "/fileshare.admin.v1.AdminService/GetServerInfo"
	// AdminServiceListSharesProcedure is the procedure name of the AdminService's ListShares RPC.
	AdminServiceListSharesProcedure = "/fileshare.admin.v1.AdminService/ListShares"
	// AdminServiceGetShareProcedure is the procedure name of the AdminService's GetShare RPC.
	AdminServiceGetShareProcedure = "/fileshare.admin.v1.AdminService/GetShare"
	// AdminServiceCreateShareProcedure is the procedure name of the AdminService's CreateShare RPC.
	AdminServiceCreateShareProcedure = "/fileshare.admin.v1.AdminService/CreateShare"
	// AdminServiceUpdateShareProcedure is the procedure name of the AdminService's UpdateShare RPC.
	AdminServiceUpdateShareProcedure = "/fileshare.admin.v1.AdminService/UpdateShare"
	// AdminServiceDeleteShareProcedure is the procedure name of the AdminService's DeleteShare RPC.
	AdminServiceDeleteShareProcedure = "/fileshare.admin.v1.AdminService/DeleteShare"
	// AdminServiceDisableShareProcedure is the procedure name of the AdminService's DisableShare RPC.
	AdminServiceDisableShareProcedure = "/fileshare.admin.v1.AdminService/DisableShare"
	// AdminServiceEnableShareProcedure is the procedure name of the AdminService's EnableShare RPC.
	AdminServiceEnableShareProcedure = "/fileshare.admin.v1.AdminService/EnableShare"
	// AdminServiceGrantProcedure is the procedure name of the AdminService's Grant RPC.
	AdminServiceGrantProcedure = "/fileshare.admin.v1.AdminService/Grant"
	// AdminServiceRevokeProcedure is the procedure name of the AdminService's Revoke RPC.
	AdminServiceRevokeProcedure = "/fileshare.admin.v1.AdminService/Revoke"
	// AdminServiceReloadDirectoryProcedure is the procedure name of the AdminService's ReloadDirectory
	// RPC.
	AdminServiceReloadDirectoryProcedure = "/fileshare.admin.v1.AdminService/ReloadDirectory"
	// AdminServiceListUsersProcedure is the procedure name of the AdminService's ListUsers RPC.
	AdminServiceListUsersProcedure = "/fileshare.admin.v1.AdminService/ListUsers"
	// AdminServiceListGroupsProcedure is the procedure name of the AdminService's ListGroups RPC.
	AdminServiceListGroupsProcedure = "/fileshare.admin.v1.AdminService/ListGroups"
	// AdminServiceListParentsProcedure is the procedure name of the AdminService's ListParents RPC.
	AdminServiceListParentsProcedure = "/fileshare.admin.v1.AdminService/ListParents"
	// AdminServiceCreateVolumeProcedure is the procedure name of the AdminService's CreateVolume RPC.
	AdminServiceCreateVolumeProcedure = "/fileshare.admin.v1.AdminService/CreateVolume"
	// AdminServiceResizeVolumeProcedure is the procedure name of the AdminService's ResizeVolume RPC.
	AdminServiceResizeVolumeProcedure = "/fileshare.admin.v1.AdminService/ResizeVolume"
	// AdminServiceSnapshotVolumeProcedure is the procedure name of the AdminService's SnapshotVolume
	// RPC.
	AdminServiceSnapshotVolumeProcedure = "/fileshare.admin.v1.AdminService/SnapshotVolume"
	// AdminServiceDeleteVolumeProcedure is the procedure name of the AdminService's DeleteVolume RPC.
	AdminServiceDeleteVolumeProcedure = "/fileshare.admin.v1.AdminService/DeleteVolume"
	// AdminServiceGetVolumeProcedure is the procedure name of the AdminService's GetVolume RPC.
	AdminServiceGetVolumeProcedure = "/fileshare.admin.v1.AdminService/GetVolume"
	// AdminServiceListVolumesProcedure is the procedure name of the AdminService's ListVolumes RPC.
	AdminServiceListVolumesProcedure = "/fileshare.admin.v1.AdminService/ListVolumes"
)

var (
	adminServiceGetServerInfoSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("GetServerInfo"),
			Procedure:  AdminServiceGetServerInfoProcedure,
		}
	})
	adminServiceListSharesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("ListShares"),
			Procedure:  AdminServiceListSharesProcedure,
		}
	})
	adminServiceGetShareSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("GetShare"),
			Procedure:  AdminServiceGetShareProcedure,
		}
	})
	adminServiceCreateShareSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("CreateShare"),
			Procedure:  AdminServiceCreateShareProcedure,
		}
	})
	adminServiceUpdateShareSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("UpdateShare"),
			Procedure:  AdminServiceUpdateShareProcedure,
		}
	})
	adminServiceDeleteShareSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("DeleteShare"),
			Procedure:  AdminServiceDeleteShareProcedure,
		}
	})
	adminServiceDisableShareSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("DisableShare"),
			Procedure:  AdminServiceDisableShareProcedure,
		}
	})
	adminServiceEnableShareSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("EnableShare"),
			Procedure:  AdminServiceEnableShareProcedure,
		}
	})
	adminServiceGrantSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("Grant"),
			Procedure:  AdminServiceGrantProcedure,
		}
	})
	adminServiceRevokeSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("Revoke"),
			Procedure:  AdminServiceRevokeProcedure,
		}
	})
	adminServiceReloadDirectorySpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("ReloadDirectory"),
			Procedure:  AdminServiceReloadDirectoryProcedure,
		}
	})
	adminServiceListUsersSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("ListUsers"),
			Procedure:  AdminServiceListUsersProcedure,
		}
	})
	adminServiceListGroupsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("ListGroups"),
			Procedure:  AdminServiceListGroupsProcedure,
		}
	})
	adminServiceListParentsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("ListParents"),
			Procedure:  AdminServiceListParentsProcedure,
		}
	})
	adminServiceCreateVolumeSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("CreateVolume"),
			Procedure:  AdminServiceCreateVolumeProcedure,
		}
	})
	adminServiceResizeVolumeSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("ResizeVolume"),
			Procedure:  AdminServiceResizeVolumeProcedure,
		}
	})
	adminServiceSnapshotVolumeSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("SnapshotVolume"),
			Procedure:  AdminServiceSnapshotVolumeProcedure,
		}
	})
	adminServiceDeleteVolumeSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("DeleteVolume"),
			Procedure:  AdminServiceDeleteVolumeProcedure,
		}
	})
	adminServiceGetVolumeSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("GetVolume"),
			Procedure:  AdminServiceGetVolumeProcedure,
		}
	})
	adminServiceListVolumesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_fileshare_admin_v1_admin_proto.Services().ByName("AdminService").Methods().ByName("ListVolumes"),
			Procedure:  AdminServiceListVolumesProcedure,
		}
	})
)

// AdminServiceClient is a client for the fileshare.admin.v1.AdminService service.
type AdminServiceClient interface {
	GetServerInfo(context.Context, *v1.GetServerInfoRequest) (*v1.GetServerInfoResponse, error)
	ListShares(context.Context, *v1.ListSharesRequest) (*v1.ListSharesResponse, error)
	GetShare(context.Context, *v1.GetShareRequest) (*v1.GetShareResponse, error)
	// CreateShare needs at least one grant. A share with none is open to
	// anyone who authenticates, which the configuration file can say on
	// purpose and an API call should not say by omission.
	CreateShare(context.Context, *v1.CreateShareRequest) (*v1.CreateShareResponse, error)
	UpdateShare(context.Context, *v1.UpdateShareRequest) (*v1.UpdateShareResponse, error)
	DeleteShare(context.Context, *v1.DeleteShareRequest) (*v1.DeleteShareResponse, error)
	// DisableShare stops serving a share and keeps its definition, the way
	// Samba's `available = no` does: every attempt to connect fails, the
	// connections already open are closed, and its image or directory is let
	// go of -- so the file can be replaced while it is disabled. EnableShare
	// serves it again, and is refused when its source can no longer be opened.
	//
	// Unlike every other change, these apply to a share of the configuration
	// too: taking a share offline is an operation, not a definition. It is
	// kept in the state file, and a restart does not bring the share back.
	DisableShare(context.Context, *v1.DisableShareRequest) (*v1.DisableShareResponse, error)
	EnableShare(context.Context, *v1.EnableShareRequest) (*v1.EnableShareResponse, error)
	// Grant gives a subject access to a share, or changes the access it has.
	Grant(context.Context, *v1.GrantRequest) (*v1.GrantResponse, error)
	// Revoke takes it away. Revoking the last grant is refused, for the reason
	// CreateShare needs one: delete the share instead.
	Revoke(context.Context, *v1.RevokeRequest) (*v1.RevokeResponse, error)
	// ReloadDirectory reads the people again, now, rather than at the next
	// `reload` interval or SIGHUP. Only additions are applied in place; any
	// removal, changed credential, or share whose expanded lists changed
	// starts a new generation and closes the connections of the old one --
	// which is how disabling somebody in the directory reaches the sessions
	// they already have. A directory that cannot be read changes nothing, and
	// is UNAVAILABLE.
	ReloadDirectory(context.Context, *v1.ReloadDirectoryRequest) (*v1.ReloadDirectoryResponse, error)
	// Who a grant can name.
	ListUsers(context.Context, *v1.ListUsersRequest) (*v1.ListUsersResponse, error)
	ListGroups(context.Context, *v1.ListGroupsRequest) (*v1.ListGroupsResponse, error)
	// ListParents is where volumes may be created, as the provisioner's own
	// configuration says.
	ListParents(context.Context, *v1.ListParentsRequest) (*v1.ListParentsResponse, error)
	// CreateVolume is idempotent by name: the same quota answers with the
	// volume that exists (created false), another is ALREADY_EXISTS.
	CreateVolume(context.Context, *v1.CreateVolumeRequest) (*v1.CreateVolumeResponse, error)
	// ResizeVolume changes the quota, either way, never below what is used.
	ResizeVolume(context.Context, *v1.ResizeVolumeRequest) (*v1.ResizeVolumeResponse, error)
	// SnapshotVolume takes a read-only snapshot (ZFS, btrfs).
	SnapshotVolume(context.Context, *v1.SnapshotVolumeRequest) (*v1.SnapshotVolumeResponse, error)
	// DeleteVolume is refused with FAILED_PRECONDITION while a share uses the
	// volume -- delete the share first. DeleteShare never deletes a volume.
	DeleteVolume(context.Context, *v1.DeleteVolumeRequest) (*v1.DeleteVolumeResponse, error)
	GetVolume(context.Context, *v1.GetVolumeRequest) (*v1.GetVolumeResponse, error)
	ListVolumes(context.Context, *v1.ListVolumesRequest) (*v1.ListVolumesResponse, error)
}

// NewAdminServiceClient constructs a client for the fileshare.admin.v1.AdminService service.
// Multiple service clients may share a single connect.Client.
func NewAdminServiceClient(client *connect.Client) AdminServiceClient {
	return &adminServiceClient{client: client}
}

// AdminServiceHandler is an implementation of the fileshare.admin.v1.AdminService service.
type AdminServiceHandler interface {
	GetServerInfo(context.Context, *v1.GetServerInfoRequest) (*v1.GetServerInfoResponse, error)
	ListShares(context.Context, *v1.ListSharesRequest) (*v1.ListSharesResponse, error)
	GetShare(context.Context, *v1.GetShareRequest) (*v1.GetShareResponse, error)
	// CreateShare needs at least one grant. A share with none is open to
	// anyone who authenticates, which the configuration file can say on
	// purpose and an API call should not say by omission.
	CreateShare(context.Context, *v1.CreateShareRequest) (*v1.CreateShareResponse, error)
	UpdateShare(context.Context, *v1.UpdateShareRequest) (*v1.UpdateShareResponse, error)
	DeleteShare(context.Context, *v1.DeleteShareRequest) (*v1.DeleteShareResponse, error)
	// DisableShare stops serving a share and keeps its definition, the way
	// Samba's `available = no` does: every attempt to connect fails, the
	// connections already open are closed, and its image or directory is let
	// go of -- so the file can be replaced while it is disabled. EnableShare
	// serves it again, and is refused when its source can no longer be opened.
	//
	// Unlike every other change, these apply to a share of the configuration
	// too: taking a share offline is an operation, not a definition. It is
	// kept in the state file, and a restart does not bring the share back.
	DisableShare(context.Context, *v1.DisableShareRequest) (*v1.DisableShareResponse, error)
	EnableShare(context.Context, *v1.EnableShareRequest) (*v1.EnableShareResponse, error)
	// Grant gives a subject access to a share, or changes the access it has.
	Grant(context.Context, *v1.GrantRequest) (*v1.GrantResponse, error)
	// Revoke takes it away. Revoking the last grant is refused, for the reason
	// CreateShare needs one: delete the share instead.
	Revoke(context.Context, *v1.RevokeRequest) (*v1.RevokeResponse, error)
	// ReloadDirectory reads the people again, now, rather than at the next
	// `reload` interval or SIGHUP. Only additions are applied in place; any
	// removal, changed credential, or share whose expanded lists changed
	// starts a new generation and closes the connections of the old one --
	// which is how disabling somebody in the directory reaches the sessions
	// they already have. A directory that cannot be read changes nothing, and
	// is UNAVAILABLE.
	ReloadDirectory(context.Context, *v1.ReloadDirectoryRequest) (*v1.ReloadDirectoryResponse, error)
	// Who a grant can name.
	ListUsers(context.Context, *v1.ListUsersRequest) (*v1.ListUsersResponse, error)
	ListGroups(context.Context, *v1.ListGroupsRequest) (*v1.ListGroupsResponse, error)
	// ListParents is where volumes may be created, as the provisioner's own
	// configuration says.
	ListParents(context.Context, *v1.ListParentsRequest) (*v1.ListParentsResponse, error)
	// CreateVolume is idempotent by name: the same quota answers with the
	// volume that exists (created false), another is ALREADY_EXISTS.
	CreateVolume(context.Context, *v1.CreateVolumeRequest) (*v1.CreateVolumeResponse, error)
	// ResizeVolume changes the quota, either way, never below what is used.
	ResizeVolume(context.Context, *v1.ResizeVolumeRequest) (*v1.ResizeVolumeResponse, error)
	// SnapshotVolume takes a read-only snapshot (ZFS, btrfs).
	SnapshotVolume(context.Context, *v1.SnapshotVolumeRequest) (*v1.SnapshotVolumeResponse, error)
	// DeleteVolume is refused with FAILED_PRECONDITION while a share uses the
	// volume -- delete the share first. DeleteShare never deletes a volume.
	DeleteVolume(context.Context, *v1.DeleteVolumeRequest) (*v1.DeleteVolumeResponse, error)
	GetVolume(context.Context, *v1.GetVolumeRequest) (*v1.GetVolumeResponse, error)
	ListVolumes(context.Context, *v1.ListVolumesRequest) (*v1.ListVolumesResponse, error)
}

// RegisterAdminServiceHandler registers svc as the fileshare.admin.v1.AdminService implementation
// on server.
func RegisterAdminServiceHandler(server *connect.Server, svc AdminServiceHandler) {
	adapter := adminServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: adminServiceGetServerInfoSpec(), Handler: adapter.getServerInfo},
		connect.Method{Spec: adminServiceListSharesSpec(), Handler: adapter.listShares},
		connect.Method{Spec: adminServiceGetShareSpec(), Handler: adapter.getShare},
		connect.Method{Spec: adminServiceCreateShareSpec(), Handler: adapter.createShare},
		connect.Method{Spec: adminServiceUpdateShareSpec(), Handler: adapter.updateShare},
		connect.Method{Spec: adminServiceDeleteShareSpec(), Handler: adapter.deleteShare},
		connect.Method{Spec: adminServiceDisableShareSpec(), Handler: adapter.disableShare},
		connect.Method{Spec: adminServiceEnableShareSpec(), Handler: adapter.enableShare},
		connect.Method{Spec: adminServiceGrantSpec(), Handler: adapter.grant},
		connect.Method{Spec: adminServiceRevokeSpec(), Handler: adapter.revoke},
		connect.Method{Spec: adminServiceReloadDirectorySpec(), Handler: adapter.reloadDirectory},
		connect.Method{Spec: adminServiceListUsersSpec(), Handler: adapter.listUsers},
		connect.Method{Spec: adminServiceListGroupsSpec(), Handler: adapter.listGroups},
		connect.Method{Spec: adminServiceListParentsSpec(), Handler: adapter.listParents},
		connect.Method{Spec: adminServiceCreateVolumeSpec(), Handler: adapter.createVolume},
		connect.Method{Spec: adminServiceResizeVolumeSpec(), Handler: adapter.resizeVolume},
		connect.Method{Spec: adminServiceSnapshotVolumeSpec(), Handler: adapter.snapshotVolume},
		connect.Method{Spec: adminServiceDeleteVolumeSpec(), Handler: adapter.deleteVolume},
		connect.Method{Spec: adminServiceGetVolumeSpec(), Handler: adapter.getVolume},
		connect.Method{Spec: adminServiceListVolumesSpec(), Handler: adapter.listVolumes},
	)
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) GetServerInfo(context.Context, *v1.GetServerInfoRequest) (*v1.GetServerInfoResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.GetServerInfo is not implemented")
}

func (UnimplementedAdminServiceHandler) ListShares(context.Context, *v1.ListSharesRequest) (*v1.ListSharesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.ListShares is not implemented")
}

func (UnimplementedAdminServiceHandler) GetShare(context.Context, *v1.GetShareRequest) (*v1.GetShareResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.GetShare is not implemented")
}

func (UnimplementedAdminServiceHandler) CreateShare(context.Context, *v1.CreateShareRequest) (*v1.CreateShareResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.CreateShare is not implemented")
}

func (UnimplementedAdminServiceHandler) UpdateShare(context.Context, *v1.UpdateShareRequest) (*v1.UpdateShareResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.UpdateShare is not implemented")
}

func (UnimplementedAdminServiceHandler) DeleteShare(context.Context, *v1.DeleteShareRequest) (*v1.DeleteShareResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.DeleteShare is not implemented")
}

func (UnimplementedAdminServiceHandler) DisableShare(context.Context, *v1.DisableShareRequest) (*v1.DisableShareResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.DisableShare is not implemented")
}

func (UnimplementedAdminServiceHandler) EnableShare(context.Context, *v1.EnableShareRequest) (*v1.EnableShareResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.EnableShare is not implemented")
}

func (UnimplementedAdminServiceHandler) Grant(context.Context, *v1.GrantRequest) (*v1.GrantResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.Grant is not implemented")
}

func (UnimplementedAdminServiceHandler) Revoke(context.Context, *v1.RevokeRequest) (*v1.RevokeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.Revoke is not implemented")
}

func (UnimplementedAdminServiceHandler) ReloadDirectory(context.Context, *v1.ReloadDirectoryRequest) (*v1.ReloadDirectoryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.ReloadDirectory is not implemented")
}

func (UnimplementedAdminServiceHandler) ListUsers(context.Context, *v1.ListUsersRequest) (*v1.ListUsersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.ListUsers is not implemented")
}

func (UnimplementedAdminServiceHandler) ListGroups(context.Context, *v1.ListGroupsRequest) (*v1.ListGroupsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.ListGroups is not implemented")
}

func (UnimplementedAdminServiceHandler) ListParents(context.Context, *v1.ListParentsRequest) (*v1.ListParentsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.ListParents is not implemented")
}

func (UnimplementedAdminServiceHandler) CreateVolume(context.Context, *v1.CreateVolumeRequest) (*v1.CreateVolumeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.CreateVolume is not implemented")
}

func (UnimplementedAdminServiceHandler) ResizeVolume(context.Context, *v1.ResizeVolumeRequest) (*v1.ResizeVolumeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.ResizeVolume is not implemented")
}

func (UnimplementedAdminServiceHandler) SnapshotVolume(context.Context, *v1.SnapshotVolumeRequest) (*v1.SnapshotVolumeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.SnapshotVolume is not implemented")
}

func (UnimplementedAdminServiceHandler) DeleteVolume(context.Context, *v1.DeleteVolumeRequest) (*v1.DeleteVolumeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.DeleteVolume is not implemented")
}

func (UnimplementedAdminServiceHandler) GetVolume(context.Context, *v1.GetVolumeRequest) (*v1.GetVolumeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.GetVolume is not implemented")
}

func (UnimplementedAdminServiceHandler) ListVolumes(context.Context, *v1.ListVolumesRequest) (*v1.ListVolumesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "fileshare.admin.v1.AdminService.ListVolumes is not implemented")
}

type adminServiceClient struct {
	client *connect.Client
}

func (c *adminServiceClient) GetServerInfo(ctx context.Context, req *v1.GetServerInfoRequest) (*v1.GetServerInfoResponse, error) {
	var res v1.GetServerInfoResponse
	if err := c.client.CallUnary(ctx, adminServiceGetServerInfoSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) ListShares(ctx context.Context, req *v1.ListSharesRequest) (*v1.ListSharesResponse, error) {
	var res v1.ListSharesResponse
	if err := c.client.CallUnary(ctx, adminServiceListSharesSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) GetShare(ctx context.Context, req *v1.GetShareRequest) (*v1.GetShareResponse, error) {
	var res v1.GetShareResponse
	if err := c.client.CallUnary(ctx, adminServiceGetShareSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) CreateShare(ctx context.Context, req *v1.CreateShareRequest) (*v1.CreateShareResponse, error) {
	var res v1.CreateShareResponse
	if err := c.client.CallUnary(ctx, adminServiceCreateShareSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) UpdateShare(ctx context.Context, req *v1.UpdateShareRequest) (*v1.UpdateShareResponse, error) {
	var res v1.UpdateShareResponse
	if err := c.client.CallUnary(ctx, adminServiceUpdateShareSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) DeleteShare(ctx context.Context, req *v1.DeleteShareRequest) (*v1.DeleteShareResponse, error) {
	var res v1.DeleteShareResponse
	if err := c.client.CallUnary(ctx, adminServiceDeleteShareSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) DisableShare(ctx context.Context, req *v1.DisableShareRequest) (*v1.DisableShareResponse, error) {
	var res v1.DisableShareResponse
	if err := c.client.CallUnary(ctx, adminServiceDisableShareSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) EnableShare(ctx context.Context, req *v1.EnableShareRequest) (*v1.EnableShareResponse, error) {
	var res v1.EnableShareResponse
	if err := c.client.CallUnary(ctx, adminServiceEnableShareSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) Grant(ctx context.Context, req *v1.GrantRequest) (*v1.GrantResponse, error) {
	var res v1.GrantResponse
	if err := c.client.CallUnary(ctx, adminServiceGrantSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) Revoke(ctx context.Context, req *v1.RevokeRequest) (*v1.RevokeResponse, error) {
	var res v1.RevokeResponse
	if err := c.client.CallUnary(ctx, adminServiceRevokeSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) ReloadDirectory(ctx context.Context, req *v1.ReloadDirectoryRequest) (*v1.ReloadDirectoryResponse, error) {
	var res v1.ReloadDirectoryResponse
	if err := c.client.CallUnary(ctx, adminServiceReloadDirectorySpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) ListUsers(ctx context.Context, req *v1.ListUsersRequest) (*v1.ListUsersResponse, error) {
	var res v1.ListUsersResponse
	if err := c.client.CallUnary(ctx, adminServiceListUsersSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) ListGroups(ctx context.Context, req *v1.ListGroupsRequest) (*v1.ListGroupsResponse, error) {
	var res v1.ListGroupsResponse
	if err := c.client.CallUnary(ctx, adminServiceListGroupsSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) ListParents(ctx context.Context, req *v1.ListParentsRequest) (*v1.ListParentsResponse, error) {
	var res v1.ListParentsResponse
	if err := c.client.CallUnary(ctx, adminServiceListParentsSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) CreateVolume(ctx context.Context, req *v1.CreateVolumeRequest) (*v1.CreateVolumeResponse, error) {
	var res v1.CreateVolumeResponse
	if err := c.client.CallUnary(ctx, adminServiceCreateVolumeSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) ResizeVolume(ctx context.Context, req *v1.ResizeVolumeRequest) (*v1.ResizeVolumeResponse, error) {
	var res v1.ResizeVolumeResponse
	if err := c.client.CallUnary(ctx, adminServiceResizeVolumeSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) SnapshotVolume(ctx context.Context, req *v1.SnapshotVolumeRequest) (*v1.SnapshotVolumeResponse, error) {
	var res v1.SnapshotVolumeResponse
	if err := c.client.CallUnary(ctx, adminServiceSnapshotVolumeSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) DeleteVolume(ctx context.Context, req *v1.DeleteVolumeRequest) (*v1.DeleteVolumeResponse, error) {
	var res v1.DeleteVolumeResponse
	if err := c.client.CallUnary(ctx, adminServiceDeleteVolumeSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) GetVolume(ctx context.Context, req *v1.GetVolumeRequest) (*v1.GetVolumeResponse, error) {
	var res v1.GetVolumeResponse
	if err := c.client.CallUnary(ctx, adminServiceGetVolumeSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *adminServiceClient) ListVolumes(ctx context.Context, req *v1.ListVolumesRequest) (*v1.ListVolumesResponse, error) {
	var res v1.ListVolumesResponse
	if err := c.client.CallUnary(ctx, adminServiceListVolumesSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type adminServiceHandler struct{ svc AdminServiceHandler }

func (h adminServiceHandler) getServerInfo(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.GetServerInfoRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetServerInfo(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) listShares(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ListSharesRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListShares(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) getShare(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.GetShareRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetShare(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) createShare(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.CreateShareRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.CreateShare(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) updateShare(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.UpdateShareRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.UpdateShare(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) deleteShare(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.DeleteShareRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.DeleteShare(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) disableShare(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.DisableShareRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.DisableShare(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) enableShare(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.EnableShareRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.EnableShare(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) grant(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.GrantRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Grant(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) revoke(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.RevokeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Revoke(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) reloadDirectory(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ReloadDirectoryRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ReloadDirectory(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) listUsers(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ListUsersRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListUsers(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) listGroups(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ListGroupsRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListGroups(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) listParents(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ListParentsRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListParents(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) createVolume(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.CreateVolumeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.CreateVolume(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) resizeVolume(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ResizeVolumeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ResizeVolume(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) snapshotVolume(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.SnapshotVolumeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.SnapshotVolume(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) deleteVolume(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.DeleteVolumeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.DeleteVolume(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) getVolume(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.GetVolumeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetVolume(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h adminServiceHandler) listVolumes(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ListVolumesRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListVolumes(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
