// SPDX-License-Identifier: BSD-3-Clause

// The provisioner's protocol: what `fileshare serve` may ask the privileged
// `fileshare provisioner` to do, and nothing else. See docs/volumes.md.
//
// It is spoken on a unix socket only, and the provisioner answers one uid --
// its configured client_uid, read from the socket with SO_PEERCRED -- with
// PERMISSION_DENIED for anybody else. The verbs are CLOSED: a method this file
// does not name, or a message that does not decode as the one it names, closes
// the connection rather than being answered (OpenSSH privsep's "unpermitted
// request"). A request carrying a field this file does not define is such a
// message: a newer client's extra field may be one the caller expects to be
// honoured, and silently ignoring it is the wrong half of that disagreement.
//
// A request never carries a path. A volume is named by a `parent` -- an id
// from the provisioner's OWN configuration -- and a `name` matched by
// ^[a-z0-9][a-z0-9_-]{0,62}$, and it lives at <parent root>/<name>. Everything
// the provisioner creates carries an ownership mark, checked before it resizes,
// snapshots or deletes anything: it never touches what it did not create.
//
// Create and Delete are idempotent by name, as CSI's are: the same name with
// the same parameters is OK and answers with the volume that exists; the same
// name with different parameters is ALREADY_EXISTS; deleting what is not there
// is OK.
//
// The status codes, CSI's vocabulary:
//
//	INVALID_ARGUMENT     a name outside the grammar, an unknown parent, a quota of 0
//	OUT_OF_RANGE         a quota above the configured max_volume
//	RESOURCE_EXHAUSTED   the parent has no room, or no project id is left
//	ALREADY_EXISTS       the name is taken with other parameters, or by something
//	                     the provisioner did not create
//	NOT_FOUND            resizing or snapshotting a volume that does not exist
//	FAILED_PRECONDITION  deleting a volume with snapshots or data without
//	                     destroy_data; shrinking below what is used; touching
//	                     something that carries no ownership mark
//	UNIMPLEMENTED        a snapshot of an XFS or ext4 volume
//	PERMISSION_DENIED    a peer whose uid is not client_uid

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: fileshare/provision/v1/provision.proto

package provisionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProvisionService_GetCapabilities_FullMethodName = "/fileshare.provision.v1.ProvisionService/GetCapabilities"
	ProvisionService_CreateVolume_FullMethodName    = "/fileshare.provision.v1.ProvisionService/CreateVolume"
	ProvisionService_ResizeVolume_FullMethodName    = "/fileshare.provision.v1.ProvisionService/ResizeVolume"
	ProvisionService_SnapshotVolume_FullMethodName  = "/fileshare.provision.v1.ProvisionService/SnapshotVolume"
	ProvisionService_DeleteVolume_FullMethodName    = "/fileshare.provision.v1.ProvisionService/DeleteVolume"
	ProvisionService_GetVolume_FullMethodName       = "/fileshare.provision.v1.ProvisionService/GetVolume"
	ProvisionService_ListVolumes_FullMethodName     = "/fileshare.provision.v1.ProvisionService/ListVolumes"
)

// ProvisionServiceClient is the client API for ProvisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvisionServiceClient interface {
	// GetCapabilities lists the parents, what kind each is, and the limits.
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	// CreateVolume creates <parent root>/<name>, limited to quota_bytes, owned
	// root:<group> mode 2770 -- fileshare writes through the group and never
	// owns it, because the OWNER of a directory may clear its XFS/ext4 project
	// id without privilege.
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	// ResizeVolume changes the quota, either way; never below what is used.
	ResizeVolume(ctx context.Context, in *ResizeVolumeRequest, opts ...grpc.CallOption) (*ResizeVolumeResponse, error)
	// SnapshotVolume takes a read-only snapshot (ZFS, btrfs). Idempotent by
	// name as CreateVolume is. UNIMPLEMENTED on XFS and ext4.
	SnapshotVolume(ctx context.Context, in *SnapshotVolumeRequest, opts ...grpc.CallOption) (*SnapshotVolumeResponse, error)
	// DeleteVolume refuses a volume with snapshots, or one that is not empty,
	// unless destroy_data is set; every delete is logged before it happens.
	DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error)
	GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
}

type provisionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvisionServiceClient(cc grpc.ClientConnInterface) ProvisionServiceClient {
	return &provisionServiceClient{cc}
}

func (c *provisionServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ProvisionService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionServiceClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, ProvisionService_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionServiceClient) ResizeVolume(ctx context.Context, in *ResizeVolumeRequest, opts ...grpc.CallOption) (*ResizeVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeVolumeResponse)
	err := c.cc.Invoke(ctx, ProvisionService_ResizeVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionServiceClient) SnapshotVolume(ctx context.Context, in *SnapshotVolumeRequest, opts ...grpc.CallOption) (*SnapshotVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotVolumeResponse)
	err := c.cc.Invoke(ctx, ProvisionService_SnapshotVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionServiceClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVolumeResponse)
	err := c.cc.Invoke(ctx, ProvisionService_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionServiceClient) GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolumeResponse)
	err := c.cc.Invoke(ctx, ProvisionService_GetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionServiceClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, ProvisionService_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionServiceServer is the server API for ProvisionService service.
// All implementations must embed UnimplementedProvisionServiceServer
// for forward compatibility.
type ProvisionServiceServer interface {
	// GetCapabilities lists the parents, what kind each is, and the limits.
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	// CreateVolume creates <parent root>/<name>, limited to quota_bytes, owned
	// root:<group> mode 2770 -- fileshare writes through the group and never
	// owns it, because the OWNER of a directory may clear its XFS/ext4 project
	// id without privilege.
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	// ResizeVolume changes the quota, either way; never below what is used.
	ResizeVolume(context.Context, *ResizeVolumeRequest) (*ResizeVolumeResponse, error)
	// SnapshotVolume takes a read-only snapshot (ZFS, btrfs). Idempotent by
	// name as CreateVolume is. UNIMPLEMENTED on XFS and ext4.
	SnapshotVolume(context.Context, *SnapshotVolumeRequest) (*SnapshotVolumeResponse, error)
	// DeleteVolume refuses a volume with snapshots, or one that is not empty,
	// unless destroy_data is set; every delete is logged before it happens.
	DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error)
	GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error)
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	mustEmbedUnimplementedProvisionServiceServer()
}

// UnimplementedProvisionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvisionServiceServer struct{}

func (UnimplementedProvisionServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedProvisionServiceServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedProvisionServiceServer) ResizeVolume(context.Context, *ResizeVolumeRequest) (*ResizeVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeVolume not implemented")
}
func (UnimplementedProvisionServiceServer) SnapshotVolume(context.Context, *SnapshotVolumeRequest) (*SnapshotVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotVolume not implemented")
}
func (UnimplementedProvisionServiceServer) DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedProvisionServiceServer) GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolume not implemented")
}
func (UnimplementedProvisionServiceServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedProvisionServiceServer) mustEmbedUnimplementedProvisionServiceServer() {}
func (UnimplementedProvisionServiceServer) testEmbeddedByValue()                          {}

// UnsafeProvisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvisionServiceServer will
// result in compilation errors.
type UnsafeProvisionServiceServer interface {
	mustEmbedUnimplementedProvisionServiceServer()
}

func RegisterProvisionServiceServer(s grpc.ServiceRegistrar, srv ProvisionServiceServer) {
	// If the following call panics, it indicates UnimplementedProvisionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvisionService_ServiceDesc, srv)
}

func _ProvisionService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionService_ResizeVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).ResizeVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_ResizeVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).ResizeVolume(ctx, req.(*ResizeVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionService_SnapshotVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).SnapshotVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_SnapshotVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).SnapshotVolume(ctx, req.(*SnapshotVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).DeleteVolume(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionService_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_GetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).GetVolume(ctx, req.(*GetVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProvisionService_ServiceDesc is the grpc.ServiceDesc for ProvisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileshare.provision.v1.ProvisionService",
	HandlerType: (*ProvisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _ProvisionService_GetCapabilities_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _ProvisionService_CreateVolume_Handler,
		},
		{
			MethodName: "ResizeVolume",
			Handler:    _ProvisionService_ResizeVolume_Handler,
		},
		{
			MethodName: "SnapshotVolume",
			Handler:    _ProvisionService_SnapshotVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _ProvisionService_DeleteVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _ProvisionService_GetVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _ProvisionService_ListVolumes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fileshare/provision/v1/provision.proto",
}
