// SPDX-License-Identifier: BSD-3-Clause

// The provisioner's protocol: what `fileshare serve` may ask the privileged
// `fileshare provisioner` to do, and nothing else. See docs/volumes.md.
//
// It is spoken on a unix socket only, and the provisioner answers one uid --
// its configured client_uid, read from the socket with SO_PEERCRED -- with
// PERMISSION_DENIED for anybody else. The verbs are CLOSED: a method this file
// does not name, or a message that does not decode as the one it names, closes
// the connection rather than being answered (OpenSSH privsep's "unpermitted
// request"). A request carrying a field this file does not define is such a
// message: a newer client's extra field may be one the caller expects to be
// honoured, and silently ignoring it is the wrong half of that disagreement.
//
// A request never carries a path. A volume is named by a `parent` -- an id
// from the provisioner's OWN configuration -- and a `name` matched by
// ^[a-z0-9][a-z0-9_-]{0,62}$, and it lives at <parent root>/<name>. Everything
// the provisioner creates carries an ownership mark, checked before it resizes,
// snapshots or deletes anything: it never touches what it did not create.
//
// Create and Delete are idempotent by name, as CSI's are: the same name with
// the same parameters is OK and answers with the volume that exists; the same
// name with different parameters is ALREADY_EXISTS; deleting what is not there
// is OK.
//
// The status codes, CSI's vocabulary:
//
//	INVALID_ARGUMENT     a name outside the grammar, an unknown parent, a quota of 0
//	OUT_OF_RANGE         a quota above the configured max_volume
//	RESOURCE_EXHAUSTED   the parent has no room, or no project id is left
//	ALREADY_EXISTS       the name is taken with other parameters, or by something
//	                     the provisioner did not create
//	NOT_FOUND            resizing or snapshotting a volume that does not exist
//	FAILED_PRECONDITION  deleting a volume with snapshots or data without
//	                     destroy_data; shrinking below what is used; touching
//	                     something that carries no ownership mark
//	UNIMPLEMENTED        a snapshot of an XFS or ext4 volume
//	PERMISSION_DENIED    a peer whose uid is not client_uid

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: fileshare/provision/v1/provision.proto

package provisionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	// A dataset <parent dataset>/<name>, refquota'd, mountpoint=legacy, mounted
	// by the provisioner at <root>/<name>.
	Kind_KIND_ZFS Kind = 1
	// A subvolume <root>/<name>, limited by its level-0 qgroup.
	Kind_KIND_BTRFS Kind = 2
	// A directory <root>/<name> under a project quota.
	Kind_KIND_XFS  Kind = 3
	Kind_KIND_EXT4 Kind = 4
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_ZFS",
		2: "KIND_BTRFS",
		3: "KIND_XFS",
		4: "KIND_EXT4",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_ZFS":         1,
		"KIND_BTRFS":       2,
		"KIND_XFS":         3,
		"KIND_EXT4":        4,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_fileshare_provision_v1_provision_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_fileshare_provision_v1_provision_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{0}
}

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{0}
}

type GetCapabilitiesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Parents []*Parent              `protobuf:"bytes,1,rep,name=parents,proto3" json:"parents,omitempty"`
	// The largest quota one volume may have.
	MaxVolumeBytes uint64 `protobuf:"varint,2,opt,name=max_volume_bytes,json=maxVolumeBytes,proto3" json:"max_volume_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapabilitiesResponse) GetParents() []*Parent {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetMaxVolumeBytes() uint64 {
	if x != nil {
		return x.MaxVolumeBytes
	}
	return 0
}

type Parent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind  Kind                   `protobuf:"varint,2,opt,name=kind,proto3,enum=fileshare.provision.v1.Kind" json:"kind,omitempty"`
	// Where its volumes are: <root>/<name>.
	Root string `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	// Free and total space of the filesystem (or, for ZFS, the dataset) the
	// volumes come from; 0 when it could not be read.
	FreeBytes  uint64 `protobuf:"varint,4,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	TotalBytes uint64 `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Whether SnapshotVolume works on its volumes.
	Snapshots     bool `protobuf:"varint,6,opt,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parent) Reset() {
	*x = Parent{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parent) ProtoMessage() {}

func (x *Parent) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parent.ProtoReflect.Descriptor instead.
func (*Parent) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{2}
}

func (x *Parent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Parent) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Parent) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *Parent) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *Parent) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *Parent) GetSnapshots() bool {
	if x != nil {
		return x.Snapshots
	}
	return false
}

type Volume struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Parent string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind   Kind                   `protobuf:"varint,3,opt,name=kind,proto3,enum=fileshare.provision.v1.Kind" json:"kind,omitempty"`
	// <parent root>/<name>, for fileshare to serve.
	Path       string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	QuotaBytes uint64 `protobuf:"varint,5,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	// What the filesystem charges to it; 0 when it could not be read.
	UsedBytes uint64                 `protobuf:"varint,6,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	Created   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	// The names of its snapshots.
	Snapshots     []string `protobuf:"bytes,8,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{3}
}

func (x *Volume) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Volume) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Volume) GetQuotaBytes() uint64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *Volume) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *Volume) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Volume) GetSnapshots() []string {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type CreateVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An id from the provisioner's own configuration, never a path.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// ^[a-z0-9][a-z0-9_-]{0,62}$
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 0 is refused: an unbounded volume is a configuration mistake.
	QuotaBytes    uint64 `protobuf:"varint,3,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVolumeRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeRequest) GetQuotaBytes() uint64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

type CreateVolumeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Volume *Volume                `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	// False when the volume already existed with these parameters.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeResponse) Reset() {
	*x = CreateVolumeResponse{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeResponse) ProtoMessage() {}

func (x *CreateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVolumeResponse) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *CreateVolumeResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ResizeVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	QuotaBytes    uint64                 `protobuf:"varint,3,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeVolumeRequest) Reset() {
	*x = ResizeVolumeRequest{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeVolumeRequest) ProtoMessage() {}

func (x *ResizeVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeVolumeRequest.ProtoReflect.Descriptor instead.
func (*ResizeVolumeRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{6}
}

func (x *ResizeVolumeRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ResizeVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResizeVolumeRequest) GetQuotaBytes() uint64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

type ResizeVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *Volume                `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeVolumeResponse) Reset() {
	*x = ResizeVolumeResponse{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeVolumeResponse) ProtoMessage() {}

func (x *ResizeVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeVolumeResponse.ProtoReflect.Descriptor instead.
func (*ResizeVolumeResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{7}
}

func (x *ResizeVolumeResponse) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

type SnapshotVolumeRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Parent string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The snapshot's own name, in the same grammar as a volume's.
	Snapshot      string `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotVolumeRequest) Reset() {
	*x = SnapshotVolumeRequest{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotVolumeRequest) ProtoMessage() {}

func (x *SnapshotVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotVolumeRequest.ProtoReflect.Descriptor instead.
func (*SnapshotVolumeRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotVolumeRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *SnapshotVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotVolumeRequest) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

type SnapshotVolumeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Volume *Volume                `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	// False when the snapshot already existed.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotVolumeResponse) Reset() {
	*x = SnapshotVolumeResponse{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotVolumeResponse) ProtoMessage() {}

func (x *SnapshotVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotVolumeResponse.ProtoReflect.Descriptor instead.
func (*SnapshotVolumeResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{9}
}

func (x *SnapshotVolumeResponse) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *SnapshotVolumeResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type DeleteVolumeRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Parent string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Destroy the volume's data and its snapshots too. Without it a volume
	// that holds either is refused with FAILED_PRECONDITION.
	DestroyData   bool `protobuf:"varint,3,opt,name=destroy_data,json=destroyData,proto3" json:"destroy_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeRequest) Reset() {
	*x = DeleteVolumeRequest{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeRequest) ProtoMessage() {}

func (x *DeleteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteVolumeRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *DeleteVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteVolumeRequest) GetDestroyData() bool {
	if x != nil {
		return x.DestroyData
	}
	return false
}

type DeleteVolumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when there was nothing to delete.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeResponse) Reset() {
	*x = DeleteVolumeResponse{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeResponse) ProtoMessage() {}

func (x *DeleteVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeResponse.ProtoReflect.Descriptor instead.
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteVolumeResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeRequest) Reset() {
	*x = GetVolumeRequest{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeRequest) ProtoMessage() {}

func (x *GetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeRequest.ProtoReflect.Descriptor instead.
func (*GetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{12}
}

func (x *GetVolumeRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *GetVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *Volume                `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeResponse) Reset() {
	*x = GetVolumeResponse{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeResponse) ProtoMessage() {}

func (x *GetVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeResponse.ProtoReflect.Descriptor instead.
func (*GetVolumeResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{13}
}

func (x *GetVolumeResponse) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

type ListVolumesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only the volumes of this parent; empty for every parent.
	Parent        string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesRequest) Reset() {
	*x = ListVolumesRequest{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesRequest) ProtoMessage() {}

func (x *ListVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListVolumesRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{14}
}

func (x *ListVolumesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type ListVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*Volume              `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesResponse) Reset() {
	*x = ListVolumesResponse{}
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesResponse) ProtoMessage() {}

func (x *ListVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_provision_v1_provision_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListVolumesResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_provision_v1_provision_proto_rawDescGZIP(), []int{15}
}

func (x *ListVolumesResponse) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

var File_fileshare_provision_v1_provision_proto protoreflect.FileDescriptor

const file_fileshare_provision_v1_provision_proto_rawDesc = "" +
	"\n" +
	"&fileshare/provision/v1/provision.proto\x12\x16fileshare.provision.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n" +
	"\x16GetCapabilitiesRequest\"}\n" +
	"\x17GetCapabilitiesResponse\x128\n" +
	"\aparents\x18\x01 \x03(\v2\x1e.fileshare.provision.v1.ParentR\aparents\x12(\n" +
	"\x10max_volume_bytes\x18\x02 \x01(\x04R\x0emaxVolumeBytes\"\xbc\x01\n" +
	"\x06Parent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1c.fileshare.provision.v1.KindR\x04kind\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x04 \x01(\x04R\tfreeBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x04R\n" +
	"totalBytes\x12\x1c\n" +
	"\tsnapshots\x18\x06 \x01(\bR\tsnapshots\"\x8e\x02\n" +
	"\x06Volume\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.fileshare.provision.v1.KindR\x04kind\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1f\n" +
	"\vquota_bytes\x18\x05 \x01(\x04R\n" +
	"quotaBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x06 \x01(\x04R\tusedBytes\x124\n" +
	"\acreated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x1c\n" +
	"\tsnapshots\x18\b \x03(\tR\tsnapshots\"b\n" +
	"\x13CreateVolumeRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vquota_bytes\x18\x03 \x01(\x04R\n" +
	"quotaBytes\"h\n" +
	"\x14CreateVolumeResponse\x126\n" +
	"\x06volume\x18\x01 \x01(\v2\x1e.fileshare.provision.v1.VolumeR\x06volume\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"b\n" +
	"\x13ResizeVolumeRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vquota_bytes\x18\x03 \x01(\x04R\n" +
	"quotaBytes\"N\n" +
	"\x14ResizeVolumeResponse\x126\n" +
	"\x06volume\x18\x01 \x01(\v2\x1e.fileshare.provision.v1.VolumeR\x06volume\"_\n" +
	"\x15SnapshotVolumeRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bsnapshot\x18\x03 \x01(\tR\bsnapshot\"j\n" +
	"\x16SnapshotVolumeResponse\x126\n" +
	"\x06volume\x18\x01 \x01(\v2\x1e.fileshare.provision.v1.VolumeR\x06volume\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"d\n" +
	"\x13DeleteVolumeRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdestroy_data\x18\x03 \x01(\bR\vdestroyData\"0\n" +
	"\x14DeleteVolumeResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\">\n" +
	"\x10GetVolumeRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"K\n" +
	"\x11GetVolumeResponse\x126\n" +
	"\x06volume\x18\x01 \x01(\v2\x1e.fileshare.provision.v1.VolumeR\x06volume\",\n" +
	"\x12ListVolumesRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\"O\n" +
	"\x13ListVolumesResponse\x128\n" +
	"\avolumes\x18\x01 \x03(\v2\x1e.fileshare.provision.v1.VolumeR\avolumes*W\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bKIND_ZFS\x10\x01\x12\x0e\n" +
	"\n" +
	"KIND_BTRFS\x10\x02\x12\f\n" +
	"\bKIND_XFS\x10\x03\x12\r\n" +
	"\tKIND_EXT4\x10\x042\x82\x06\n" +
	"\x10ProvisionService\x12r\n" +
	"\x0fGetCapabilities\x12..fileshare.provision.v1.GetCapabilitiesRequest\x1a/.fileshare.provision.v1.GetCapabilitiesResponse\x12i\n" +
	"\fCreateVolume\x12+.fileshare.provision.v1.CreateVolumeRequest\x1a,.fileshare.provision.v1.CreateVolumeResponse\x12i\n" +
	"\fResizeVolume\x12+.fileshare.provision.v1.ResizeVolumeRequest\x1a,.fileshare.provision.v1.ResizeVolumeResponse\x12o\n" +
	"\x0eSnapshotVolume\x12-.fileshare.provision.v1.SnapshotVolumeRequest\x1a..fileshare.provision.v1.SnapshotVolumeResponse\x12i\n" +
	"\fDeleteVolume\x12+.fileshare.provision.v1.DeleteVolumeRequest\x1a,.fileshare.provision.v1.DeleteVolumeResponse\x12`\n" +
	"\tGetVolume\x12(.fileshare.provision.v1.GetVolumeRequest\x1a).fileshare.provision.v1.GetVolumeResponse\x12f\n" +
	"\vListVolumes\x12*.fileshare.provision.v1.ListVolumesRequest\x1a+.fileshare.provision.v1.ListVolumesResponseBLZJgithub.com/go-fileshare/fileshare/proto/fileshare/provision/v1;provisionv1b\x06proto3"

var (
	file_fileshare_provision_v1_provision_proto_rawDescOnce sync.Once
	file_fileshare_provision_v1_provision_proto_rawDescData []byte
)

func file_fileshare_provision_v1_provision_proto_rawDescGZIP() []byte {
	file_fileshare_provision_v1_provision_proto_rawDescOnce.Do(func() {
		file_fileshare_provision_v1_provision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fileshare_provision_v1_provision_proto_rawDesc), len(file_fileshare_provision_v1_provision_proto_rawDesc)))
	})
	return file_fileshare_provision_v1_provision_proto_rawDescData
}

var file_fileshare_provision_v1_provision_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fileshare_provision_v1_provision_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_fileshare_provision_v1_provision_proto_goTypes = []any{
	(Kind)(0),                       // 0: fileshare.provision.v1.Kind
	(*GetCapabilitiesRequest)(nil),  // 1: fileshare.provision.v1.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil), // 2: fileshare.provision.v1.GetCapabilitiesResponse
	(*Parent)(nil),                  // 3: fileshare.provision.v1.Parent
	(*Volume)(nil),                  // 4: fileshare.provision.v1.Volume
	(*CreateVolumeRequest)(nil),     // 5: fileshare.provision.v1.CreateVolumeRequest
	(*CreateVolumeResponse)(nil),    // 6: fileshare.provision.v1.CreateVolumeResponse
	(*ResizeVolumeRequest)(nil),     // 7: fileshare.provision.v1.ResizeVolumeRequest
	(*ResizeVolumeResponse)(nil),    // 8: fileshare.provision.v1.ResizeVolumeResponse
	(*SnapshotVolumeRequest)(nil),   // 9: fileshare.provision.v1.SnapshotVolumeRequest
	(*SnapshotVolumeResponse)(nil),  // 10: fileshare.provision.v1.SnapshotVolumeResponse
	(*DeleteVolumeRequest)(nil),     // 11: fileshare.provision.v1.DeleteVolumeRequest
	(*DeleteVolumeResponse)(nil),    // 12: fileshare.provision.v1.DeleteVolumeResponse
	(*GetVolumeRequest)(nil),        // 13: fileshare.provision.v1.GetVolumeRequest
	(*GetVolumeResponse)(nil),       // 14: fileshare.provision.v1.GetVolumeResponse
	(*ListVolumesRequest)(nil),      // 15: fileshare.provision.v1.ListVolumesRequest
	(*ListVolumesResponse)(nil),     // 16: fileshare.provision.v1.ListVolumesResponse
	(*timestamppb.Timestamp)(nil),   // 17: google.protobuf.Timestamp
}
var file_fileshare_provision_v1_provision_proto_depIdxs = []int32{
	3,  // 0: fileshare.provision.v1.GetCapabilitiesResponse.parents:type_name -> fileshare.provision.v1.Parent
	0,  // 1: fileshare.provision.v1.Parent.kind:type_name -> fileshare.provision.v1.Kind
	0,  // 2: fileshare.provision.v1.Volume.kind:type_name -> fileshare.provision.v1.Kind
	17, // 3: fileshare.provision.v1.Volume.created:type_name -> google.protobuf.Timestamp
	4,  // 4: fileshare.provision.v1.CreateVolumeResponse.volume:type_name -> fileshare.provision.v1.Volume
	4,  // 5: fileshare.provision.v1.ResizeVolumeResponse.volume:type_name -> fileshare.provision.v1.Volume
	4,  // 6: fileshare.provision.v1.SnapshotVolumeResponse.volume:type_name -> fileshare.provision.v1.Volume
	4,  // 7: fileshare.provision.v1.GetVolumeResponse.volume:type_name -> fileshare.provision.v1.Volume
	4,  // 8: fileshare.provision.v1.ListVolumesResponse.volumes:type_name -> fileshare.provision.v1.Volume
	1,  // 9: fileshare.provision.v1.ProvisionService.GetCapabilities:input_type -> fileshare.provision.v1.GetCapabilitiesRequest
	5,  // 10: fileshare.provision.v1.ProvisionService.CreateVolume:input_type -> fileshare.provision.v1.CreateVolumeRequest
	7,  // 11: fileshare.provision.v1.ProvisionService.ResizeVolume:input_type -> fileshare.provision.v1.ResizeVolumeRequest
	9,  // 12: fileshare.provision.v1.ProvisionService.SnapshotVolume:input_type -> fileshare.provision.v1.SnapshotVolumeRequest
	11, // 13: fileshare.provision.v1.ProvisionService.DeleteVolume:input_type -> fileshare.provision.v1.DeleteVolumeRequest
	13, // 14: fileshare.provision.v1.ProvisionService.GetVolume:input_type -> fileshare.provision.v1.GetVolumeRequest
	15, // 15: fileshare.provision.v1.ProvisionService.ListVolumes:input_type -> fileshare.provision.v1.ListVolumesRequest
	2,  // 16: fileshare.provision.v1.ProvisionService.GetCapabilities:output_type -> fileshare.provision.v1.GetCapabilitiesResponse
	6,  // 17: fileshare.provision.v1.ProvisionService.CreateVolume:output_type -> fileshare.provision.v1.CreateVolumeResponse
	8,  // 18: fileshare.provision.v1.ProvisionService.ResizeVolume:output_type -> fileshare.provision.v1.ResizeVolumeResponse
	10, // 19: fileshare.provision.v1.ProvisionService.SnapshotVolume:output_type -> fileshare.provision.v1.SnapshotVolumeResponse
	12, // 20: fileshare.provision.v1.ProvisionService.DeleteVolume:output_type -> fileshare.provision.v1.DeleteVolumeResponse
	14, // 21: fileshare.provision.v1.ProvisionService.GetVolume:output_type -> fileshare.provision.v1.GetVolumeResponse
	16, // 22: fileshare.provision.v1.ProvisionService.ListVolumes:output_type -> fileshare.provision.v1.ListVolumesResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_fileshare_provision_v1_provision_proto_init() }
func file_fileshare_provision_v1_provision_proto_init() {
	if File_fileshare_provision_v1_provision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fileshare_provision_v1_provision_proto_rawDesc), len(file_fileshare_provision_v1_provision_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileshare_provision_v1_provision_proto_goTypes,
		DependencyIndexes: file_fileshare_provision_v1_provision_proto_depIdxs,
		EnumInfos:         file_fileshare_provision_v1_provision_proto_enumTypes,
		MessageInfos:      file_fileshare_provision_v1_provision_proto_msgTypes,
	}.Build()
	File_fileshare_provision_v1_provision_proto = out.File
	file_fileshare_provision_v1_provision_proto_goTypes = nil
	file_fileshare_provision_v1_provision_proto_depIdxs = nil
}
